classic/example/intermediate/regex_convert.cpp, doc/qi/error_handling.qbk, include/boost/spirit/home/support/detail/lexer/parser/parser.hpp, include/boost/spirit/repository/home/qi/directive/kwd.hpp, include/boost/spirit/repository/home/qi/operator/keywords.hpp, repository/doc/qi/keywords.qbk, repository/doc/qi/kwd.qbk, repository/example/qi/keywords.cpp
Fix spelling of occurrence/occurred.
=> Fix spelling of "occurr*".

include/boost/spirit/home/x3/directive.hpp, test/x3/extensions/confix.cpp, test/x3/extensions/repeat.cpp, test/x3/extensions/seek.cpp, test/x3/matches.cpp
Now the x3 testsuite builds again.
=> Fix include paths.

include/boost/spirit/home/x3/binary.hpp, include/boost/spirit/home/x3/binary/binary.hpp, test/x3/Jamfile, test/x3/binary.cpp, test/x3/test.hpp
This is not polished yet, and doesn't support floating point types. Consider this as pre-review pull request.
Comments are expected and welcome.
=> Add support for the binary parsers

test/x3/sequence.cpp
A fix should always be acompanied with a test, methinks.
Finally figured out how to test for this (it was sooo easy, gah)
=> X3: Add test for the fix in 2a94b18e976ade8ae2b454831ea4d8b89111abb3.

classic/test/loops_tests.cpp, classic/test/parametric_tests.cpp, classic/test/primitives_tests.cpp, classic/test/rule_tests.cpp, classic/test/scanner_tests.cpp, classic/test/subrule_tests.cpp, classic/test/switch_tests_eps_default.cpp, classic/test/switch_tests_general_def.cpp, classic/test/switch_tests_single.cpp, classic/test/switch_tests_wo_default.cpp
=> Ticket 10975

include/boost/spirit/home/qi/numeric/detail/real_impl.hpp
This fixes warnings issued by MSVC 14.0.
=> Fix for MSVC 14.0 type conversion warnings

include/boost/spirit/home/classic/core/non_terminal/impl/subrule.ipp
without it trying to build quickbook fails for me with an error in MSVC 15.
=> Added header for mpl::if_

include/boost/spirit/home/x3/support/traits/move_to.hpp
Fix bug described here - http://article.gmane.org/gmane.comp.lib.boost.devel/266211
=> fixes problem with move_to

include/boost/spirit/home/x3/support/traits/container_traits.hpp, test/x3/container_support.cpp
Using boost TTI library to replace hand-written TTI code.
=> Using boost TTI library to replace hand-written TTI code.

include/boost/spirit/home/x3/nonterminal/detail/rule.hpp
One comment to much in my last pull request, sorry.
=> fix wrong out commented parameter in x3::detail::make_rule_context(...)

include/boost/spirit/home/qi/directive/expect.hpp
Fixes compilation errors after merging PR #196.
=> Fix missing include for expectation_failure

doc/qi/operator.qbk
a%b not equivalent to a >> *(b >> a)
See conversation of PR #208.
=> Qi: Fix of list operator documentation (replaces PR#208)

include/boost/spirit/home/x3/nonterminal/simple_trace.hpp, include/boost/spirit/home/x3/operator/and_predicate.hpp
=> Crash when print attribute in debug mode.

include/boost/spirit/home/x3/nonterminal/simple_trace.hpp, include/boost/spirit/home/x3/operator/and_predicate.hpp
=> Revert "Crash when print attribute in debug mode."

include/boost/spirit/home/classic/core/non_terminal/impl/grammar.ipp
This fixes issues with clang5 and C++17 mode
=> Removing use of bind2nd

include/boost/spirit/home/support/detail/hold_any.hpp
=> Fix scary warning in hold_any

meta/explicit-failures-markup.xml
Replaces boostorg/boost#172.
Commit-bot should merge this to super-repo automatically.
=> Define test categories

test/x3/Jamfile
=> X3.Tests: Add c++14 feature checks

include/boost/spirit/home/x3/operator/detail/sequence.hpp, include/boost/spirit/home/x3/support/traits/attribute_category.hpp, include/boost/spirit/home/x3/support/traits/move_to.hpp, test/x3/optional.cpp
PR for issue #250 "optional_attribute is useless in x3/support/traits/attribute_category.hpp"
=> optional_attribute

test/x3/error_handler.cpp
Fixes error_handler test for msvc-14.0
=> error_handler test msvc-14.0

include/boost/spirit/home/karma/auxiliary/attr_cast.hpp, include/boost/spirit/repository/home/karma/directive/confix.hpp, include/boost/spirit/repository/home/qi/directive/confix.hpp, include/boost/spirit/repository/home/qi/directive/distinct.hpp, include/boost/spirit/repository/home/qi/directive/kwd.hpp, include/boost/spirit/repository/home/qi/operator/keywords.hpp, include/boost/spirit/repository/home/qi/primitive/advance.hpp, include/boost/spirit/repository/home/qi/primitive/flush_multi_pass.hpp
Closes https://svn.boost.org/trac10/ticket/13311
=> Fixed problems with BOOST_SPIRIT_NO_PREDEFINED_TERMINALS

include/boost/spirit/home/x3/core/action.hpp, include/boost/spirit/home/x3/core/call.hpp, include/boost/spirit/home/x3/core/detail/parse_into_container.hpp, include/boost/spirit/home/x3/directive/expect.hpp, include/boost/spirit/home/x3/directive/lexeme.hpp, include/boost/spirit/home/x3/directive/no_case.hpp, include/boost/spirit/home/x3/directive/no_skip.hpp, include/boost/spirit/home/x3/directive/omit.hpp, include/boost/spirit/home/x3/directive/skip.hpp, include/boost/spirit/home/x3/numeric/bool_policies.hpp, include/boost/spirit/home/x3/numeric/real_policies.hpp, include/boost/spirit/home/x3/operator/alternative.hpp, include/boost/spirit/home/x3/operator/and_predicate.hpp, include/boost/spirit/home/x3/operator/detail/alternative.hpp, include/boost/spirit/home/x3/operator/detail/sequence.hpp, include/boost/spirit/home/x3/operator/difference.hpp, include/boost/spirit/home/x3/operator/kleene.hpp, include/boost/spirit/home/x3/operator/list.hpp, include/boost/spirit/home/x3/operator/not_predicate.hpp, include/boost/spirit/home/x3/operator/optional.hpp, include/boost/spirit/home/x3/operator/plus.hpp, include/boost/spirit/home/x3/operator/sequence.hpp, include/boost/spirit/home/x3/support/numeric_utils/extract_real.hpp, include/boost/spirit/home/x3/support/numeric_utils/sign.hpp
Closes #257 and https://svn.boost.org/trac10/ticket/12084
=> X3: Fixed include guard names collision

doc/faq.qbk, doc/karma/auxiliary.qbk, doc/karma/complex.qbk, doc/karma/quick_reference.qbk, doc/lex/lexer_quickstart2.qbk, doc/lex/lexer_quickstart3.qbk, doc/lex/lexer_semantic_actions.qbk, doc/lex/quick_reference.qbk, doc/notes/porting_from_1_8.qbk, doc/preface.qbk, doc/qi/quick_reference.qbk, doc/spirit2.qbk, doc/what_s_new.qbk, repository/doc/spirit2_repository.qbk
=> Fix phoenix links

include/boost/spirit/home/x3/support/traits/container_traits.hpp, test/x3/Jamfile
- Fixes #298 and is based on https://github.com/boostorg/spirit/commit/45902cbb4e949e7543bcf48d3a4ed1247cab4f6b provided by @Kojoley 
- Added container_support.cpp to x3 test suite again
=> Fix container traits for msvc

include/boost/spirit/home/karma/numeric/detail/real_utils.hpp, test/karma/real3.cpp
https://svn.boost.org/trac10/ticket/5983
https://svn.boost.org/trac10/ticket/12599
Added suggested fix and test.
Yeah, two bug trackers... See https://github.com/boostorg/spirit/pull/224
=> Stack overflow with Karma floating point generator

doc/qi/numeric.qbk
Closes https://svn.boost.org/trac10/ticket/7638. Credits to @K-ballo.
=> Qi.Doc: Fixed bool policies signature

include/boost/spirit/home/x3/numeric/real_policies.hpp
=> Prevent parse_nan() from dereferencing out of range iterator

doc/karma/concepts.qbk, doc/qi/concepts.qbk
=> Nonterminal doc fixes

README.md
=> Extend README with info of Spirit libraries

classic/change_log.html, doc/refcard/spirit-reference.tex, doc/spirit2.qbk, doc/what_s_new.qbk, doc/x3/changelog.qbk, doc/x3/spirit_x3.qbk, include/boost/spirit/home/classic/version.hpp, include/boost/spirit/home/x3/version.hpp, include/boost/spirit/include/version.hpp
I hope I did not forget to change the numbers somewhere else.
=> Bump version and update changelog [skip ci]

include/boost/spirit/home/x3/operator/list.hpp
One iterator copy operation less on any input.
=> Small list parser optimization

include/boost/spirit/home/support/algorithm/any_if_ns.hpp, include/boost/spirit/home/support/algorithm/any_if_ns_so.hpp
This is follow-up to 0f2b3c49ce55a41a7d22cc5533e0f4ba59e491ae
=> Qi: Fixed ADT support by permutation and sequence_or operator

doc/what_s_new.qbk
ref : https://github.com/boostorg/website/pull/316
=> [1.67.0] fix issue URL

include/boost/spirit/home/qi/stream/detail/iterator_source.hpp
Optimizing this case allows the compiler to achieve a large speedup
especially in the case where the underlying range is contiguous in
memory.
The effective result is for the performance to be equivalent to directly
using `boost::iostreams::array_source<char_type>` if the source range so
allows.
This patch arose from benchmarking several varying approaches to parsing
posix timestamps here:
- https://stackoverflow.com/questions/49693376/why-does-using-a-stream-in-boost-spirit-penalize-performance-so-much
- https://stackoverflow.com/questions/49671674/use-a-trait-for-parsing-a-date-in-boostspirit
I'll refer to that location for some benchmark results.
=> Specialize iterator_source for random access

include/boost/spirit/home/classic/core/primitives/primitives.hpp
I have missed the thing that by incrementing scanner it runs skipper too.
=> Classic: The right fix for PR 336

include/boost/spirit/home/classic/error_handling/exceptions.hpp, include/boost/spirit/home/classic/iterator/multi_pass.hpp, include/boost/spirit/home/qi/detail/expectation_failure.hpp, include/boost/spirit/home/support/detail/lexer/runtime_error.hpp, include/boost/spirit/home/support/iterators/detail/buf_id_check_policy.hpp, include/boost/spirit/home/support/utree/utree.hpp, include/boost/spirit/home/x3/directive/expect.hpp
https://gcc.gnu.org/wiki/Visibility#Problems_with_C.2B-.2B-_exceptions_.28please_read.21.29
=> Missing visibility mark on exception types

doc/qi/nonterminal.qbk, doc/qi/quick_reference.qbk
=> Qi: Improve documentation for semantic actions in %=

include/boost/spirit/home/x3/nonterminal/detail/rule.hpp, include/boost/spirit/home/x3/nonterminal/detail/transform_attribute.hpp, include/boost/spirit/home/x3/support/traits/transform_attribute.hpp, test/x3/actions.cpp, test/x3/alternative.cpp, test/x3/rule3.cpp
=> X3: Ensure symmetric transforms

include/boost/spirit/home/karma/binary/binary.hpp, include/boost/spirit/home/qi/binary/binary.hpp, include/boost/spirit/home/support/detail/endian/endian.hpp
=> Do not spoil endian namespace

.appveyor.yml, include/boost/spirit/home/classic/core/assert.hpp, include/boost/spirit/home/karma/directive/omit.hpp, include/boost/spirit/home/karma/numeric/detail/numeric_utils.hpp, include/boost/spirit/home/qi/numeric/real_policies.hpp, include/boost/spirit/home/x3/char/detail/cast_char.hpp, include/boost/spirit/home/x3/support/numeric_utils/detail/extract_int.hpp, include/boost/spirit/repository/home/qi/directive/kwd.hpp, include/boost/spirit/repository/home/qi/operator/detail/keywords.hpp, include/boost/spirit/repository/home/qi/operator/keywords.hpp, test/karma/regression_adapt_adt.cpp, test/qi/extract_int.cpp, test/qi/range_run.cpp, test/x3/extract_int.cpp
=> Fix MSVC C4127 warnings

include/boost/spirit/home/classic/tree/common.hpp, include/boost/spirit/home/support/detail/lexer/parser/tokeniser/num_token.hpp, include/boost/spirit/home/support/iterators/istream_iterator.hpp, include/boost/spirit/home/support/utree/utree.hpp
Still cannot reenable -Wdeprecated-copy on CI because of Fusion, Phoenix, Proto, and Random
=> Fix -Wdeprecated-copy

include/boost/spirit/home/x3/binary/binary.hpp, test/x3/binary.cpp
=> X3: binary parser floating point types support

include/boost/spirit/home/x3/operator/detail/alternative.hpp, test/x3/alternative.cpp
This seems like a good compromise until we find a general solution.
Closes #434
=> X3: Sequence parser in alternative into container

include/boost/spirit/home/x3/support/traits/is_substitute.hpp, test/x3/container_support.cpp, test/x3/rule3.cpp
Match same arguments early to break infinity recursion.
Closes #461
=> X3: Infinity recursion in `is_substitute`

include/boost/spirit/home/x3/operator/alternative.hpp, include/boost/spirit/home/x3/operator/detail/alternative.hpp, include/boost/spirit/home/x3/operator/detail/sequence.hpp, include/boost/spirit/home/x3/operator/sequence.hpp, include/boost/spirit/home/x3/support/traits/attribute_of_binary.hpp
=> X3: Attribute of alternative/sequence without MPL

include/boost/spirit/home/x3/operator/detail/alternative.hpp, include/boost/spirit/home/x3/support/traits/move_to.hpp, test/x3/alternative.cpp
Moreover, guard ourselves from this ever happening again.
=> X3: Fixed self-move in alternative parser

include/boost/spirit/home/support/char_encoding/unicode.hpp, include/boost/spirit/home/support/char_set/range_functions.hpp, include/boost/spirit/home/x3/support/traits/print_attribute.hpp, include/boost/spirit/home/x3/support/traits/print_token.hpp, test/x3/symbols3.cpp
=> Revert "Use char32_t as unicode encoding char_type"

include/boost/spirit/home/karma/numeric/detail/real_utils.hpp, test/karma/real2.cpp, test/karma/real3.cpp
=> Fixing problems related to formatting numbers

include/boost/spirit/home/qi/directive/raw.hpp, include/boost/spirit/home/x3/directive/raw.hpp, test/qi/raw.cpp, test/x3/raw.cpp
=> raw directive handles_container should alway be true

include/boost/spirit/home/x3/char/char_class.hpp, test/x3/char_class.cpp
6821c8208b0d763aabb17f79a7be9b3714f6c80c port to X3
Closes #675
=> X3: Fix encoding char cast type

include/boost/spirit/home/x3/directive/seek.hpp, repository/test/qi/seek.cpp, test/x3/seek.cpp
=> X3: Fix seek goes past the end of input

include/boost/spirit/home/karma/numeric/real_policies.hpp, test/karma/real3.cpp
=> Karma: real generator off by a magnitude due to log10 rounding up

include/boost/spirit/home/support/iterators/line_pos_iterator.hpp, test/support/line_pos_iterator.cpp
=> line_pos_iterator: fix multiple consequence CRLF/LFCR handling

CMakeLists.txt, include/boost/spirit/home/support/utf8.hpp, include/boost/spirit/home/x3/support/utility/utf8.hpp
Another little step towards standalone X3.
=> Cease dependence on Boost.Regex
