include/boost/spirit/home/classic/utility/impl/chset.ipp

Removes unused parameters that Clang 3.6 is warning on.

Removed unused parameters, caught by clang warnings.

---

include/boost/spirit/home/karma/numeric/detail/real_utils.hpp

This change fixes a C4244 compiler warning issued by MSVC 12.0.

Fix for a type conversion warning

---

include/boost/spirit/home/x3/support/ast/variant.hpp

I ran into some compile-time errors when trying to copy an object of a type derived from x3::variant.
The root of the issue seems to be the SFINAE check on the members operator=; namely: when variant's move-assignment operator template is considered during overload resolution, it deduces 'A&' for template parameter T, and then reference-collapsing transforms 'variant& &&' into 'variant&', and thus the template ends up being a better choice than the implicitly-declared copy-assignment operator. This leads to a nice tall error message.
It seems like we just need a test for "self" as part of the SFINAE check on that operator template---which we used to have, but it appears to have been commented out at some point (for reasons not immediately clear to me).
In this commit, four of the member …

Updated the check-for-self in x3::variant

---

include/boost/spirit/home/lex/lexer/string_token_def.hpp

g++ 4.9.2 generates -Wunused-local-typedefs as follows;
```
/home/tabe/isopt/boost_1_58_0/include/boost/spirit/home/lex/lexer/string_token_def.hpp: In member function ‘void boost::spirit::lex::string_token_def<String, IdType, CharEncoding>::collect(LexerDef&, const String_&, const String_&) const’:
/home/tabe/isopt/boost_1_58_0/include/boost/spirit/home/lex/lexer/string_token_def.hpp:104:48: warning: typedef ‘id_type’ locally defined but not used [-Wunused-local-typedefs]
typedef typename LexerDef::id_type id_type;
^
```

fix unused local typedef

---

include/boost/spirit/home/lex/argument.hpp

Found another -Wunused-local-typedefs:
```
/home/tabe/isopt/boost_1_58_0/include/boost/spirit/home/lex/argument.hpp: In member function ‘void boost::spirit::lex::state_setter< <template-parameter-1-1> >::eval(const Env&) const’:
/home/tabe/isopt/boost_1_58_0/include/boost/spirit/home/lex/argument.hpp:104:60: warning: typedef ‘string’ locally defined but not used [-Wunused-local-typedefs]
typedef typename context_type::state_name_type string;
^
```

fix another unused local typedef

---

example/x3/rexpr/rexpr_full/rexpr/rexpr.hpp
include/boost/spirit/home/x3/nonterminal/detail/rule.hpp

Have rexpr include rule.hpp independently as a check.

Allow rule.hpp to be included independently.

---

example/x3/calc/calc8/annotation.hpp
example/x3/calc/calc9/annotation.hpp
example/x3/rexpr/rexpr_full/rexpr/annotation.hpp

There is no need fetch the error_handler and call its tag method twice.

Kill duplicated code in annotation.hpp.

---

include/boost/spirit/home/x3/operator/detail/alternative.hpp
include/boost/spirit/home/x3/operator/detail/sequence.hpp

This is a follow-up to 20170960dcf5203871ffbec14f64f97a647364b2 which fixes
x3::alternative, but omitted x3::sequence.

X3: Fix push_back to mpl::view in x3::sequence.

---

include/boost/spirit/home/classic/core/primitives/primitives.hpp

I get loads of warnings about this unused typedef when building QuickBook.

Removed unused result_t

---

include/boost/spirit/home/lex/lexer/lexertl/functor_data.hpp

This avoids a warning like:
```
/some/path/include/boost/spirit/home/lex/lexer/lexertl/functor_data.hpp:171:42: warning: unused parameter ‘it’ [-Wunused-parameter]
void set_end(Iterator const& it) {}
^
```

fix unused parameter

---

include/boost/spirit/home/x3/core/parser.hpp
include/boost/spirit/home/x3/operator/alternative.hpp
include/boost/spirit/home/x3/operator/sequence.hpp

For consistency with the rest.  Apparently, this brings the executable size of
an X3 grammar of mine down from 440936 to 420000.  It also reduces compilation
time a bit, which was rather unexpected (18.3s to 17.8s).

X3: Avoid copying the arguments to {unary,binary}_parser, sequence and alternative.

---

include/boost/spirit/home/x3/operator/alternative.hpp

This is actually a logical-or, so use one.

X3: Simplify alternative::parse.

---

include/boost/spirit/home/x3/core/parser.hpp

These are completely redundant.

X3: Remove useless using-directives.

---

include/boost/spirit/home/x3/nonterminal/rule.hpp

A tiny change which results in 7kb less binary size and 17.8s to 17.2s compile
time reduction (GCC).

X3: Add another missing const&.

---

include/boost/spirit/home/x3/support/subcontext.hpp
include/boost/spirit/home/x3/support/unused.hpp

This is a follow-up to 6ede5f7c8129c4fbcfb09d8762f26e0cbd64b1c6.

X3: Eliminate two more hidden cases of get_result.

---

include/boost/spirit/home/x3/support/utility/is_callable.hpp

boost/utility/result_of.hpp is rather expensive to include. Using decltype
here makes the compile time go down by almost half a sec.

X3: Use decltype instead of result_of.

---

include/boost/spirit/home/x3/support/utility/error_reporting.hpp

position_cache allows to retrieve the iterator_range of a position tagged AST
type.  However, pos_cache in error_handler<Iterator> is private, so the
iterator_range can not be retrieved from client code. It would be useful for a
"late raw" and for testing purposes. This patch adds
error_handler<Iterator>::position_of(position_tagged).

Allow retrieval of the iterator_range of a position_tagged.

---

classic/test/rule_tests.cpp

Now that the "using namespace std" has been removed, endl has to be qualified with "std::".

Compile fix

---

include/boost/spirit/home/qi/numeric/detail/real_impl.hpp

This is a fix for the issue posted on the mailing list. I don't see any other unitialized data values. I don't think a test can be written unless `n` is initialized, otherwise the test will be unreliable (n _usually_ equals some small nearly zero value on my box, but it is undefined ....).

Unitialized data fix

---

include/boost/spirit/home/x3/char/char_set.hpp
test/x3/char1.cpp

These small changes should fix the behaviour described in [ticket 11531](https://svn.boost.org/trac/boost/ticket/11531).

X3: Fix char_range boundaries

---

include/boost/spirit/home/qi/numeric/detail/numeric_utils.hpp

Static variables depend on each other and when static init is not thread-safe, this leads to race condition and failures. Ticket: https://svn.boost.org/trac/boost/ticket/11514

Fixing race condition on static init

---

include/boost/spirit/home/qi/detail/assign_to.hpp

since commit 69cc5370381e48352dc01c708599e9b49b7460f0 (hkaiser hkaiser
authored on 7 Nov 2009) spirit support BOOST_FUSION_ADAPT_ADT adapted
structs was broken

reenabled support for BOOST_FUSION_ADAPT_ADT adapted structs

---

include/boost/spirit/home/karma/string/lit.hpp

Hello,
I submit this tiny cleanup PR since this causes the following warning (treated as error)
```
...
include/boost/spirit/home/karma/string/lit.hpp: In member function 'bool boost::spirit::karma::literal_string<String, CharEncoding, Tag, no_attribute>::gen
erate(OutputIterator&, Context&, const Delimiter&, const Attribute&) const':
include/boost/spirit/home/karma/string/lit.hpp:179:17: error: typedef 'extracted_string_type' locally defined but not used [-Werror=unused-local-typedefs]
extracted_string_type;
^
cc1plus: all warnings being treated as errors
```
The definition of _extracted_string_type_  was introduced by commit 555ce82 and its use removed some days later through 2d4f293. So I guess this local definition can be safely removed.
To you for validation.
Regards, …

Fix local typedef definition warning

---

include/boost/spirit/home/qi/detail/assign_to.hpp

Defect introduced by new code in a4f9ea9d58303b0d6a4347bcea4f30a9fdddebd2

Fix: remove extraneous 'typename'

---

include/boost/spirit/home/classic/tree/parse_tree.hpp

Hi,
When building against Spirit with -Wall -Wextra and gcc 4.9, we get:
79:42: error: typedef 'attr_t' locally defined but not used [-Werror=unused-local-typedefs]
typedef typename match_t::attr_t attr_t;
in file include/boost/spirit/home/classic/tree/parse_tree.hpp.
This patch fixes it.
Cheers,
Romain

Fix "unused locally defined typedef" in parse_tree.hpp

---

example/lex/word_count_lexer.cpp

Problem reported via http://stackoverflow.com/questions/32786820/cant-compile-boost-spirit-word-count-lexer-example

Fix compile error in word_count_lexer example

---

include/boost/spirit/home/support/attributes.hpp
include/boost/spirit/home/support/terminal.hpp

First commit avoids compile error on partial specialization in c++11 due to deprecation.
Second commit removes use of undocumented fusion::void_.

Support variadic fusion.

---

classic/test/Jamfile

see [spirit/classic - action_tests](http://www.boost.org/development/tests/develop/developer/output/teeks99-01a-Ubuntu14-04-64-boost-bin-v2-libs-spirit-classic-test-action_tests-test-gcc-5-1-debug.html) and [spirit/classic - action_tests_debug](http://www.boost.org/development/tests/develop/developer/output/teeks99-01a-Ubuntu14-04-64-boost-bin-v2-libs-spirit-classic-test-action_tests_debug-test-gcc-5-1-debug.html).

Fix link error on classic's regression test.

---

include/boost/spirit/home/support/detail/endian/endian.hpp

Undefined behavior sanitizer (UBSan) with GCC 5.1.1 complains about left
shifting of negative value at run-time. This happens once
boost::spirit::detail::load_little_endian is used with a singed type.
The patch resolves the issue by using unsigned type for making left shifts,
then load_little_endian casts it to specific type T.
Tested with Clang and GCC locally (test case in #11726) and all worked fine.
Tested by running all Boost test cases before and after, no regressions.
Signed-off-by: David Abdurachmanov <david.abdurachmanov@gmail.com>

[develop] Fix undefined behavior in ../support/detail/endian/endian.hpp (#11726)

---

include/boost/spirit/home/karma/directive/duplicate.hpp
test/karma/duplicate.cpp

An expression such as `generate(..., (duplicate[double_ << double_] | "foo"), 2.0)` will output "foo" even though `duplicate[double_ << double_]` should never fail. The problem is that `duplicate` adds a reference to the reported attribute type. The `is_convertible` check will fail, causing the first branch of the alternative to be ignored at compile-time.
All of the tests were run on OSX with this patch - no issues. I leave it to the spirit braintrust to determine whether this could cause any issues with code in the wild.

Fixed bug in karma::duplicate attribute reporting

---

include/boost/spirit/home/support/detail/endian/endian.hpp

Undefined behavior sanitizer (UBSan) with GCC 5.1.1 complains about left
shifting of negative value at run-time. This happens once
boost::spirit::detail::load_little_endian is used with a singed type.
The patch resolves the issue by using unsigned type for making left shifts,
then load_little_endian casts it to specific type T.
Tested with Clang and GCC locally (test case in #11726) and all worked fine.
Tested by running all Boost test cases before and after, no regressions.
C++ standard reference: 5.8 section "Shift operators", 2nd paragraph.
Signed-off-by: David Abdurachmanov <david.abdurachmanov@gmail.com>

Fix undefined behavior in ../support/detail/endian/endian.hpp (#11726)

---

include/boost/spirit/home/support/terminal.hpp

Silence mass MSVC-14 warnings:
boost/spirit/home/support/terminal.hpp(264): warning C4348: 'boost::spirit::terminal<boost::spirit::tag::lit>::result_helper': redefinition of default parameter: parameter 3
boost/spirit/home/support/terminal.hpp(270): note: see declaration of 'boost::spirit::terminal<boost::spirit::tag::lit>::result_helper'
boost/spirit/home/support/common_terminals.hpp(142): note: see reference to class template instantiation 'boost::spirit::terminal<boost::spirit::tag::lit>' being compiled
boost/spirit/home/support/terminal.hpp(264): warning C4348: 'boost::spirit::terminal<boost::spirit::tag::lit>::result_helper': redefinition of default parameter: parameter 4
boost/spirit/home/support/terminal.hpp(270): note: see declaration of …

Silence MSVC warnings

---

include/boost/spirit/home/qi/string/tst_map.hpp

It is used later in find(), so complete type is needed. Include tst.hpp which defines it.
Test program:
```
#include <boost/spirit/home/qi/string/tst_map.hpp>
int main() {
boost::spirit::qi::tst_map<char, int> map;
int* x;
map.find(x, x);
return 0;
}
```
Clang output:
```
In file included from test.cc:1:
/usr/local/include/boost/spirit/home/qi/string/tst_map.hpp:74:38: error: invalid use of incomplete type 'boost::spirit::qi::tst_pass_through'
return find(first, last, tst_pass_through());
^~~~~~~~~~~~~~~~~~
/usr/local/include/boost/spirit/home/qi/string/tst_map.hpp:20:12: note: forward declaration of 'boost::spirit::qi::tst_pass_through'
struct tst_pass_through; // declared in tst.hpp
^
1 error generated.
```
gcc output:
```
In file included from test.cc:1:0: …
```

Don't forward declare struct tst_pass_through

---

include/boost/spirit/home/classic/core/non_terminal/impl/grammar.ipp

Hi,
I am currently facing issues when using -Werror and gcc 4.9, the compiler is complaining about unused local typedef.
Cheers,
Romain

Fix "unused local typedefs" in grammar.ipp

---

include/boost/spirit/home/x3/support/traits/container_traits.hpp
test/x3/container_support.cpp

Cleaned up push_back_container and append_container.
Removed reserve optimization in append_container since we must provide reserve for different container types (e.g. string and deque) and the container implementation should decide how to append elements as fast as possible.

Cleaned up container_traits.

---

include/boost/spirit/home/classic/core/non_terminal/impl/rule.ipp

This caused compile breaks when building Boost.Serialization.

Add missing include for mpl::if_

---

include/boost/spirit/home/x3/string/literal_string.hpp

The rule x3::lit("H\x02\x00"s) is currently broken, because x3::lit delegates the c_str() to literal_string.
So the string is truncated at '\x00'.
Instead we should delegate the string. Then x3::lit("H\x02\x00"s) works fine.

x3::lit should delegate std::basic_string<Char> instead of Char*

---

include/boost/spirit/home/x3/nonterminal/detail/rule.hpp
test/x3/debug.cpp

dbg_attribute_type(attr_) creates a temporary that is bound to const reference inside of context_debug.
This will fail on assert:
#define BOOST_SPIRIT_X3_DEBUG
#include <iostream>
#include <boost/spirit/home/x3.hpp>
namespace x3 = boost::spirit::x3;
struct p
{
bool alive = true;
void access() const
{
assert(alive);
}
~p()
{
alive = false;
}
};
std::ostream & operator << (std::ostream & os, p o)
{
o.access();
return os << "o";
}
x3::symbols<p> s
{
{
{ "s", p{} }
},
"s"
};
auto r = x3::rule<struct r, p>{ "r" } = s;
int main()
{
std::string str = "s";
auto b = str.begin();
auto e = str.end();
p v;
phrase_parse(b, e, r, x3::blank, v) && b == e;
}

dangling reference to attribute when BOOST_SPIRIT_X3_DEBUG is defined

---

include/boost/spirit/home/x3/directive/expect.hpp
include/boost/spirit/home/x3/operator/detail/alternative.hpp
test/x3/alternative.cpp

Removed `parse_into_container_impl` specializations for `alternative` and `expect`. `alternative` now exposes the inner attribute directly when both branches are the same. All tests pass, including test case from [bug 12094](https://svn.boost.org/trac/boost/ticket/12094).
If the alternative parser has matching two element sequences, the sequence is not correctly flattened with the neighboring sequence, i.e.:
```c++
int_ >> ((int_ >> int_) | (int_ >> int_))
```
This will be done next.

Update exposed attribute for alternative parser

---

test/x3/alternative.cpp

X3 already works when given a `boost::optional` attribute, although I did not see any test cases for this in X3. I think the behavior in Qi and X3 are now similar - only the expected attribute differed between the versions.
I did not implement the sequence flattening with the alternative parser, as Qi does not do this! Will post to mailing list shortly.

Added boost::optional test case to X3 alternative parser from Qi

---

include/boost/spirit/home/x3/nonterminal/rule.hpp

The `rule_` parameter is not used in `parse_rule`, which `BOOST_SPIRIT_DEFINE` expands to. GCC with `-Wunused-parameter` (often indirectly activated by `-Wall -Wextra`) issues a warning when a function parameter is not used in its function body.

Suppress an "unused parameter" warning of rule_

---

include/boost/spirit/home/support/iterators/multi_pass.hpp
test/Jamfile
test/support/istream_iterator_basic.cpp

This should resolve TRAC #12166 and add some test coverage for istream_iterator (including the fix).

Simple tests for istream_iterator and a fix for multi_pass_iterator

---

include/boost/spirit/home/classic/core/non_terminal/impl/grammar.ipp
include/boost/spirit/home/classic/symbols/impl/tst.ipp
include/boost/spirit/home/support/detail/lexer/generator.hpp

Hi,
I am having issues when using json_spirit and boost 1.61 with GCC 6 and -std=gnu++14 -Wall -Werror -Wextra.
This removes all the last auto_ptr references in boost spirit. Inspired by https://svn.boost.org/trac/boost/ticket/11672.
I have tested with json_spirit and boost 1.61, then ported to the branch "develop" as is.
Cheers,
Romain

Remove auto_ptr (deprecated in recent C++ standards).

---

include/boost/spirit/home/classic/phoenix/special_ops.hpp

This breaks for clang as the NDK namespaces are oddly set up.
The old version works for gcc builds on Android, but clang is now the default compiler with gcc deprecated.
Isn't the declaration undefined behaviour anyway?

Don't try to declare std::complex for Android builds

---

example/qi/expect.cpp
include/boost/spirit/home/qi/detail/expectation_failure.hpp
include/boost/spirit/home/qi/directive/expect.hpp
include/boost/spirit/home/qi/nonterminal/debug_handler.hpp
include/boost/spirit/home/qi/operator/expect.hpp
include/boost/spirit/include/version.hpp
test/qi/expectd.cpp

his PR contains fixes for both issues reported by Lastique and
MarcelRaad. It makes PR #197 obsolete.
Removed obsolete dependency  of test/qi/expectd.cpp on
mxc/qitoo/qitoo.hpp. Was reintroduced by mistake.
Created qi/detail/expectation_failure.hpp. It defines the
expectation_failure template as a common dependency of expect directive
and expect operator. Removed expectation_failure from
operator/expect.hpp.
Changed dependency of debug_handler.hpp to from operator/expect.hpp to expectation_failure.hpp.
Changed version.hpp to 2.54. I did not notice that addl file in the
first place.

Fixes for PR #196 expect directive

---

include/boost/spirit/home/qi/directive/expect.hpp

After moving expectation_failure to detail/expectation_failure.hpp as of PR #198 there is no longer a dependency on operator/expect.hpp.

Undo header inclusion from PR #197 (obsolete because of PR #198 being merged)

---

include/boost/spirit/home/lex/qi/plain_token.hpp
test/Jamfile
test/lex/plain_token.cpp

plain_token_range has a bug where it really only checks for equality against the bottom of the range supplied.  This patch restores the intended behavior.

Repair plain_token_range and add tests

---

include/boost/spirit/home/support/detail/lexer/generator.hpp

Lex is using `unique_ptr` from `movelib` and relying on a bug in it, described in [a ticket](https://svn.boost.org/trac/boost/ticket/11758).
Since that bug fixed in `movelib` Lex is uncompilable.
I have simplified unique_ptr usage by the following rules:
- `delete ptr.release()` is equal to `ptr.reset()`
- `delete a.release(); a = b;` is equal to `b.swap(a); b.reset();`
Now Lex test suite compiles and runs succesfully. VC++ 6 should be happy too despite the fact that Boost no longer supports it.

Lex: Fixed unique_ptr usage

---

example/qi/reference.cpp

Error message:
> qi/reference.cpp:1047:31: error: ‘expect’ was not declared in this scope
>              test_parser("xi", expect[char_('o')]); // should throw an exception
Introduced with PR #196 (commit d494fe189b447b359d88f188d95d4e40ef3997ff)

Qi.Examples: Fixed missing `using` statement for `expect` directive

---

test/qi/alternative.cpp

Logic of the test is to prevent direct left recursion, but
currently because of it `b2` fails to compile `alternative.cpp`.
I have wrapped the case with `SPIRIT_NO_COMPILE_CHECK` like it
has been done in `char1.cpp` and `sequence.cpp` tests.
Actually the test fails at compilation only with std >= c++11,
but passes with std <= c++03.
PS: I do know that `alternative.cpp` does not compile for a
different reason too (because of problem described in #201)

Qi.Tests: Wrap `r1 = r1 | eps` with `SPIRIT_NO_COMPILE_CHECK` macro

---

include/boost/spirit/home/qi/detail/alternative_function.hpp

For me it looks like an issue involving the type traits `not_is_variant` and `not_is_optional`. `boost::optionals` which contain a `boost::variant`  (`boost::optional<boost::variant>`) are treated as variants, i.e. `not_is_variant` gives `mpl::false_`. 
This leads to `call_optional_or_variant` gets called with `mpl::false_` which seems to be incorrect for this type. 
Because `not_is_variant` and `not_is_optional` are not mutually exclusive in that context, I changed that to continue with `mpl::true` if the Attribute is an optional.
With that change the test case compiles. 
But I am actually not sure about the intention behind treating optionals as variants by the traits. If this design produces side effects qi relies on, my change might be not sufficient. 
The spirit_v2/qi test suite …

Fix for spirit_v2 qi/alternative test case

---

include/boost/spirit/home/qi/numeric/detail/real_impl.hpp

Fixes the following warning message from the Intel compiler:
> boost/spirit/home/qi/numeric/detail/real_impl.hpp(34): warning #780:
>  using-declaration ignored -- it refers to the current namespace

Qi: `pow10` is already in the `spirit::traits` namespace

---

include/boost/spirit/home/qi/detail/alternative_function.hpp

The bug was introduced in PR #201

Qi: Fixed missing space in the nested template

---

test/support/utree.cpp

Fixes following warnings:
```
gcc.compile.c++ ../../../bin.v2/libs/spirit/test/support_utree-p3.test/gcc-5/debug/coverage-on/support/utree.o
In file included from ../../../boost/detail/lightweight_test.hpp:15:0,
from support/utree.cpp:11:
support/utree.cpp: In function ‘int main()’:
support/utree.cpp:351:35: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
BOOST_TEST(!utree(true)   == utree(false));
^
../../../boost/core/lightweight_test.hpp:146:28: note: in definition of macro ‘BOOST_TEST’
#define BOOST_TEST(expr) ((expr)? (void)0: ::boost::detail::test_failed_impl(#expr, __FILE__, __LINE__, BOOST_CURRENT_FUNCTION))
^
support/utree.cpp:352:35: warning: logical not is only applied to the left hand side of comparison …
```

Tests: Fix warnings from `support/utree.cpp` test

---

test/lex/regression_wide.cpp

Full list:
```
lex/regression_wide.cpp:69:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
BOOST_TEST(sequence_counter < sizeof(data)/sizeof(data[0]));
^
lex/regression_wide.cpp:70:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
BOOST_TEST(data[sequence_counter].tokenid == tokenid);
^
lex/regression_wide.cpp:93:11: warning: field 'constant' will be initialized after field 'operation' [-Wreorder]
, constant  (L"[0-9]+(\\.[0-9]+)?", ID_CONSTANT)
^
lex/regression_wide.cpp:122:52: warning: unused typedef 'iterator_type' [-Wunused-local-typedef]
typedef mega_tokens<lexer_type>::iterator_type iterator_type;
^
```

Lex.Tests: Fixed multiple warning from `regression_wide` test

---

test/karma/bool.cpp

```
warning: incrementing expression of type bool is deprecated and incompatible with C++1z [-Wdeprecated-increment-bool]
karma/bool.cpp:120:40: note: in instantiation of template class 'boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::pre_inc, boost::proto::argsns_::list1<boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::reference_wrapper<bool> >, 0> > >, 1> >' requested here
BOOST_TEST(test("true", bool_, ++phoenix::ref(b)));
^
```

Karma.Tests: Fixed bool increment warning

---

test/karma/pattern4.cpp
test/lex/dedent_handling_phoenix.cpp
test/lex/token_iterpair.cpp

```
lex/token_iterpair.cpp:111:49: warning: unused variable 'value' [-Wunused-variable]
typename Token::token_value_type const& value (t.value());
^
lex/token_iterpair.cpp:129:49: warning: unused variable 'value' [-Wunused-variable]
typename Token::token_value_type const& value (t.value());
^
karma/pattern4.cpp: In function ‘int main()’:
karma/pattern4.cpp:82:44: warning: typedef ‘var_type’ locally defined but not used [-Wunused-local-typedefs]
typedef variant<char, int, double> var_type;
^
karma/pattern4.cpp:100:44: warning: typedef ‘var_type’ locally defined but not used [-Wunused-local-typedefs]
typedef variant<char, int, double> var_type;
^
lex/dedent_handling_phoenix.cpp: In function ‘int main()’:
lex/dedent_handling_phoenix.cpp:86:39: warning: typedef ‘iterator’ locally defined but …
```

Tests: Fixed multiple unused variable warnings

---

test/qi/utree1.cpp

Fixes this warnings from Clang:
```
qi/utree1.cpp:171:49: warning: overloaded operator >> has higher precedence than comparison operator [-Woverloaded-shift-op-parentheses]
BOOST_TEST(test_attr("a25.5b", r3 >> r2 > r1, ut));
~~~~~~~~ ^ ~~
qi/utree1.cpp:171:43: note: place parentheses around the '>>' expression to silence this warning
BOOST_TEST(test_attr("a25.5b", r3 >> r2 > r1, ut));
~~~^~~~~
qi/utree1.cpp:171:49: note: place parentheses around comparison expression to evaluate it first
BOOST_TEST(test_attr("a25.5b", r3 >> r2 > r1, ut));
~~~^~~~
qi/utree1.cpp:181:49: warning: overloaded operator >> has higher precedence than comparison operator [-Woverloaded-shift-op-parentheses]
BOOST_TEST(test_attr("a25.5b", r3 >> r2 > char_, ut));
~~~~~~~~ ^ ~~~~~
qi/utree1.cpp:181:43: note: place …
```

Qi.Tests: utree1: Fixed operator precedence warnings [clang]

---

test/karma/regression_real_0.cpp
test/lex/regression_less_8563.cpp
test/lex/regression_static_wide_6253.cpp

Fixes following warnings:
```
karma_regression_real_0-p3
..\libs\spirit\test\karma\regression_real_0.cpp:15:15: warning: unused parameter 'argc' [-Wunused-parameter]
..\libs\spirit\test\karma\regression_real_0.cpp:15:28: warning: unused parameter 'argv' [-Wunused-parameter]
regression_less_8563-p3
..\libs\spirit\test\lex\regression_less_8563.cpp:30:14: warning: unused parameter 'argc' [-Wunused-parameter]
..\libs\spirit\test\lex\regression_less_8563.cpp:30:31: warning: unused parameter 'argv' [-Wunused-parameter]
regression_static_wide_6253-p3
..\libs\spirit\test\lex\regression_static_wide_6253.cpp:31:14: warning: unused parameter 'argc' [-Wunused-parameter]
..\libs\spirit\test\lex\regression_static_wide_6253.cpp:31:31: warning: unused parameter 'argv' [-Wunused-parameter]
```

Tests: Removed unused `argc` and `argv` parameters

---

include/boost/spirit/home/qi/detail/construct.hpp

The terminal tags `boost::spirit::[u]long_long_type` hide the integer types `boost::[u]long_long_types`, qualify the later.

Fix assign_to_attribute_from_iterators for long long types

---

include/boost/spirit/home/qi/numeric/detail/numeric_utils.hpp

Hi,
I am having troubles when including "boost/spirit/include/qi.hpp" with gcc 6 and -Wall -Werror turned on. gcc (wrongly) complains about misleading indentation in the macro SPIRIT_NUMERIC_INNER_LOOP. This is likely caused by the fact that we have extra indentation after each line so that the backlslashes are properly aligned, and the macro is eventually putting this on a single line. Anyway, an easy fix is to use braces around all block of code.
Ok for the merge ?
Cheers,
Romain

Fix gcc's warning/error when building with -Wmisleading-indentation

---

include/boost/spirit/home/karma/auxiliary/lazy.hpp
include/boost/spirit/home/karma/nonterminal/rule.hpp

This should fix some small warnings detected by clang 3.9.0 with -Wall -Wextra -Werror.

Fix clang unused paramter warning.

---

include/boost/spirit/home/support/detail/pow10.hpp

Fixes [Ticket #12642](https://svn.boost.org/trac/boost/ticket/12642). The optimized pow10 function would not be used unless cfloat had already been externally included.

Fix float parser missing optimization

---

include/boost/spirit/home/classic/error_handling/exceptions.hpp

Hi,
Here is a small warning fix in classic/error_handling/exceptions.hpp when using gcc 4.9 and -Wall -Wextra:
boost/spirit/home/classic/error_handling/exceptions.hpp:143:51: warning: typedef 'iterator_t' locally defined but not used [-Wunused-local-typedefs]
             typedef typename ScannerT::iterator_t iterator_t;
Ok for the trunk ?
Cheers,
Romain

Fix warning "typedef 'iterator_t' locally defined but not used" in classic/error_handling/exceptions.hpp

---

include/boost/spirit/home/x3/core/parser.hpp
include/boost/spirit/home/x3/nonterminal/rule.hpp

(reported by Exagon http://stackoverflow.com/a/41785268/85371)
Due to [Static Initialization Order Fiasco](https://isocpp.org/wiki/faq/ctors#static-init-order) sometimes X3 parsing aborts with a `std::logic_error`. The cause is unitialized `rule::name` fields.
It is clear that the design of Spirit X3 has accounted for static initialization order in that the `parse_rule` specializations contain function-local instances that defeat the issue.
However, the rule name initialization lives inside the namespace-scope static variable and its initialization is not guarded. This is probably an oversight.
Unfortunately I don't think there is a clean/elegant solution that will not introduce more function-local statics (with their syntax and runtime overhead).
This PR adds diagnostics to detect when a …

std::logic_error - Initialization Order Fiasco

---

include/boost/spirit/home/x3/nonterminal/detail/rule.hpp

There is an issue in `call_rule_definition` where it tries to print the
attribute before transformation (via `context_debug` -> `simple_trace`).
However, it breaks if the made attribute type doesn't match the actual
attribute type. In this case, it makes `context_debug` store a dangling
reference to a temporary converted attribute, leading to Undefined
Behaviour.
See also https://stackoverflow.com/a/43688320/85371

Fix dangling refs in debug of call_rule_defintion`

---

include/boost/spirit/home/lex/lexer/lexertl/functor.hpp

Remove a PGI-specific workaround in the functor constructor.  The workaround was necessary several years ago to get class functor to compiler with PGI, but the workaround now causes compilation errors.

Update PGI C++ compiler support

---

include/boost/spirit/home/x3/directive/with.hpp
test/x3/with.cpp

1. when used as x3::with<ID>(x), where x is an lvalue, we inject an lvalue reference of x to the context.
2. when used as x3::with<ID>(x), where x is a const lvalue, we inject a const lvalue reference of x to the context.
3. when used as x3::with<ID>(x), where x is an rvalue, we move the rvalue to the member of with_directive and inject an lvalue reference of that member to the context.
4. No copy is applied; std::ref can still be used but not needed.
5. remove unused with_context

simplify with directive

---

include/boost/spirit/home/x3/binary/binary.hpp
include/boost/spirit/home/x3/char/char_set.hpp
include/boost/spirit/home/x3/directive/confix.hpp
include/boost/spirit/home/x3/numeric/bool.hpp
include/boost/spirit/home/x3/numeric/real.hpp

fix parsers like x3::skip(x3::space)[x3::double_] compile problem
x3 directives like skip, with and no_case create an rvalue context therefore cannot bind with Context&. Besides, we are not really changing the context in these places (all the other places use Context const& already). I think using const& is fine here. 
The example seems rare, but it could be a blocking issue if we want to use these directives on a generic parser.

Context& -> Context const&

---

include/boost/spirit/home/x3/support/ast/variant.hpp

This adds `noexcept` specifications to X3's `variant` and `forward_ast`. Missing specs on the types' move constructors was showing up in my profiling and I decided to fix up the types in whole.
I wasn't sure whether to use `noexcept` directly or `BOOST_NOEXCEPT`/`BOOST_NOEXCEPT_IF`; I couldn't find any precedent so opted for the latter.

Add noexcept specs to x3::variant and forward_ast

---

include/boost/spirit/home/qi/numeric/detail/numeric_utils.hpp

With -Wlogical-op, gcc warns in radix_traits::is_valid with Radix <= 10:
```
boost/spirit/home/qi/numeric/detail/numeric_utils.hpp: In instantiation of ‘static bool boost::spirit::qi::detail::radix_traits<10u>::is_valid<char>(char)’:
[...]
boost/spirit/home/qi/numeric/detail/numeric_utils.hpp:107:31: warning: logical ‘and’ of mutually exclusive tests is always false [-Wlogical-op]
|| (ch >= 'a' && ch <= static_cast<Char>('a' + Radix -10 -1))
^
boost/spirit/home/qi/numeric/detail/numeric_utils.hpp:108:31: warning: logical ‘and’ of mutually exclusive tests is always false [-Wlogical-op]
|| (ch >= 'A' && ch <= static_cast<Char>('A' + Radix -10 -1));
^
```
Rather than suppressing the warning (https://github.com/boostorg/spirit/pull/77), refactor the test so that the warning is not triggered.

Avoid -Wlogical-op warning/error in radix_traits::is_valid

---

doc/x3/quick_reference.qbk
doc/x3/spirit_x3.qbk

As far as I can tell, `as`, `as_string`, and `as_wstring` are not part of X3.

Remove as, as_string, and as_wstring from X3's documentation.

---

include/boost/spirit/home/lex/lexer/lexertl/token.hpp

When compiling with -fsanitize=undefined, `lexertl::token::id()` fails in lex_id_type_enum-p3:
```
../../../boost/spirit/home/lex/lexer/lexertl/token.hpp:161:37: runtime error: load of value 4294967295, which is not a valid value for type 'token_id'
#0 0x41b212 in boost::spirit::lex::lexertl::token<boost::spirit::classic::position_iterator2<boost::spirit::multi_pass<std::istreambuf_iterator<char, std::char_traits<char> >, boost::spirit::iterator_policies::default_policy<boost::spirit::iterator_policies::ref_counted, boost::spirit::iterator_policies::no_check, boost::spirit::iterator_policies::buffering_input_iterator, boost::spirit::iterator_policies::split_std_deque> >, boost::spirit::classic::file_position_base<std::__cxx11::basic_string<char, std::char_traits<char>, …
```

Store id as promoted type to allow out-of-enum values

---

include/boost/spirit/home/x3/support/utility/error_reporting.hpp

On systems where a line is terminated by CR+LF, the position() function only
counts as one a sequence of empty lines.
Because the most common line terminations (according to Wikipedia) are \n, \r
and \r\n, I propose to only check previous char for \n. Unfortunately, this will
more or less double the counted number of lines on any system using \n\r
(but I don't this is worth doing something smarter!)
MD

x3::error_handler::position() CR+LF lines wrongly counted.

---

example/x3/calc/calc8/config.hpp
example/x3/calc/calc9/config.hpp
example/x3/rexpr/rexpr_full/rexpr/config.hpp

`with_context` was removed in 361b12eeeb703fb8daa6ecc4e8714653b4c8dbe8 (#239) but the examples had not been adjusted.

X3.Examples: Fix `no template named 'with_context'` error

---

example/qi/reference.cpp

Error message:
```
qi/reference.cpp:126:5: note: candidate function template not viable: requires 3 arguments, but 4 were provided
parse_frac_n(Iterator& first, Iterator const& last, Attribute& attr)
```
The issue had been introduced in 6832dc229872d7f9573a506cfe1ed640dc79871e where `parse_frac_n` signature was changed.

Qi.Examples: Fixed `parse_frac_n` in `reference.cpp`

---

include/boost/spirit/repository/home/qi/operator/detail/keywords.hpp

Though `result` specializations should be symmetrical to `operator()`, in this particular case author used 'hacky' way and I did not touch this, only fixed compilation error and done it in the same way as it is in other places e.g. https://github.com/boostorg/spirit/blob/9a8cded55355644c749d6511504b59c048d64de3/include/boost/spirit/home/karma/operator/alternative.hpp#L65-L69

Qi.Repository: Fix `keywords` compilation on c++11

---

include/boost/spirit/home/karma/detail/output_iterator.hpp

It seems that `no_buffering_policy` had a copy-paste error for 8 years.
Found it at compilation of `example/karma/simple_columns_directive.cpp`
<details>
<summary>GCC</summary>
```
gcc.compile.c++ ../../../bin.v2/libs/spirit/example/karma/gcc-gnu-6/debug/threadapi-pthread/simple_columns_directive.o
In file included from ../../../boost/spirit/home/karma/detail/generate.hpp:16:0,
from ../../../boost/spirit/home/karma/generate.hpp:15,
from ../../../boost/spirit/home/karma/generate_attr.hpp:11,
from ../../../boost/spirit/include/karma_generate_attr.hpp:16,
from karma/simple_columns_directive.cpp:12:
../../../boost/spirit/home/karma/detail/output_iterator.hpp: In instantiation of ‘boost::spirit::karma::detail::output_iterator_base<Buffering, Counting, Tracking>::output_iterator_base(const …
```

Karma: Fixed `no_buffering_policy` missing copy constructor

---

example/karma/complex_number_adapt.cpp

Added missing `boost/spirit/include/support_adapt_adt_attributes.hpp` include

Karma.Examples: Fix complex_number_adapt compilation

---

test/Jamfile

The test was added in 90d65d4be785050f65eeee03769cfb995c4adf5b,
but still is not used in the test suite.

Karma.Tests: Added `regression_real_policy_sign.cpp` to test suite

---

example/qi/reference.cpp

Phoenix expression used like it is a Qi expression.
I suspect it had been legal when they were belong to the same Proto domain but not now.
Closes #260

Qi.Examples: reference: Fixed lazy example

---

include/boost/spirit/home/x3/core/detail/parse_into_container.hpp

Passing `unused_type` attribute to `parse_into_container_impl::call` produces a compilation error (clang: https://travis-ci.org/Kojoley/spirit/jobs/298783103 gcc: https://travis-ci.org/Kojoley/spirit/jobs/298783104).
The issue was introduced in 379413a50c93539aa432fa9f9fc94fec1d6aa60d.
While the fix restores x3 test suite (checked on msvc, gcc, clang) I am not quite sure it is the right solution. @djowel please, review the fix.

X3: Fix `unused_type` attribute case in `parse_into_container`

---

include/boost/spirit/home/classic/core/match.hpp

`boost::optional<T &>` has member named `argument_type`
I do not know when it did break because defining `BOOST_OPTIONAL_CONFIG_USE_OLD_IMPLEMENTATION_OF_OPTIONAL` does not solve the problem.
P.S: I thought `conditional<is_reference<T>::value, T, T const&>::type` should work, but GCC barks on `T const&` if `T` is reference (while MSVC and Clang are completely fine with it).

Classic: Fixed compilation of `match<T &>`

---

include/boost/spirit/repository/home/karma/nonterminal/subrule.hpp
include/boost/spirit/repository/home/qi/nonterminal/subrule.hpp

This fixes a long standing bugs persisted in `subrule` for years.
Those `%=` operator overloads are awful, but I do not know other solution (It should be possible to [tell proto to disable operators](http://www.boost.org/doc/libs/1_65_1/doc/html/proto/users_guide.html#boost_proto.users_guide.front_end.customizing_expressions_in_your_domain.inhibiting_overloads) but I do not know spirit's internals well enough for doing that).
Tested on VS2017, clang 5.0 c++03/1y, gcc 6 c++03/1y

Fix `subrule` compilation

---

include/boost/spirit/repository/home/karma/nonterminal/subrule.hpp
include/boost/spirit/repository/home/qi/nonterminal/subrule.hpp

The problem is that `f(T&)` and `f(T&&)` overloads had the same priority
http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1164
Affected compilers are:
- MSVC 9/10/11
- GCC 4.7.2, 4.8.4 with `-std=c++1x`

Repository: subrule: Fixed partial ordering problem

---

test/qi/uint1.cpp

Fixes compilation problem on MSVC 8/9

Qi.Tests: uint1: Fixed `uint8_t` usage

---

test/support/regression_multi_pass_position_iterator.cpp

Maybe will fix and MSVC 8 too. The fix found accidentally.
<details>
<summary>The actual error</summary>
```
compile-c-c++ ..\..\..\..\bin.v2\libs\spirit\test\support\support_regression_multi_pass_position_iterator-p3.test\msvc-9\debug\threadapi-win32\threading-multi\support_regression_multi_pass_position_iterator-p3.obj
regression_multi_pass_position_iterator.cpp
boost/spirit/home/qi/skip_over.hpp(27) : error C3767: '!=': candidate function(s) not accessible
could be the friend function at 'boost/spirit/home/qi/skip_flag.hpp(24)' : '!='  [may be found via argument-dependent lookup]
or the friend function at       'boost/spirit/home/qi/skip_flag.hpp(24)' : '!='  [may be found via argument-dependent lookup]
or the friend function at       'boost/spirit/home/qi/skip_flag.hpp(24)' : '!=' …
```

Support.Tests: regression_multi_pass_position_iterator: Fixed MSVC 9 compilation

---

include/boost/spirit/repository/home/karma/nonterminal/subrule.hpp
include/boost/spirit/repository/home/qi/nonterminal/subrule.hpp

It took me 3 days of pulling my hair to debug and fix the bug. The subrule's author put a big bomb under it and I caught the exposition only in a single test, with modern versions of Clang/GCC and enabled optimizations (most of boost regression test runners does not use `variant=release`). Valgrind did not catch any problems. Enabling address sanitizer causes the bug to disappear (now I understand why, it places big gaps between stack pointers). `-fsanitize-address-use-after-scope` catches the bug, but I have discovered that it is turned off in Clang by default after already having a repro.
The bug could be easily reproduced if you use any parser that invalidates it's state in the destructor.
I used `literal_char` with added `~literal_char() { ch = char_type(0); }`.
Reproduction code: …

subrule: Fixed a huge use after scope bug

---

.travis.yml

I have chosen to run builds with `warnings-as-errors=on` to ensure that PRs bring no new warning.
`warnings=on` still produces some warning, they are suppressed by `known-warnings=suppress`. 
I did not enable `warnings=all` because it requires more work while `warnings=on` is not yet completed.
Clang builds faster than GCC, so I chose to bootstrap using `--with-toolset=clang`.
I have place Boost libraries built as a separate step so it do not spoil the tests log and it will show a build error rather than a tests failure.
Testing with `variant=release` because most (even if not all) the boost test runners use `variant=debug` (implicitly, I have figured it out while dealing bug in subrules; according to docs, without a `variant=` argument it should be `variant=release` by default on linux, …

Add Travis-CI

---

include/boost/spirit/home/classic/core/composite/actions.hpp
include/boost/spirit/home/classic/dynamic/impl/switch.ipp

Discovered in a boost uuid coverity scan:
https://scan4.coverity.com/reports.htm#v17121/p12449/fileInstanceId=27630727&defectInstanceId=5505434&mergedDefectId=58160&eventId=5505434-0

silence coverity discovery of ignored return code from at_end

---

include/boost/spirit/home/qi/numeric/detail/numeric_utils.hpp
include/boost/spirit/home/qi/numeric/numeric_utils.hpp
include/boost/spirit/home/x3/support/numeric_utils/detail/extract_int.hpp
include/boost/spirit/home/x3/support/numeric_utils/extract_int.hpp
test/qi/uint1.cpp
test/x3/uint1.cpp

According to spirit document,
"All numeric parsers check for overflow conditions based on the type T the corresponding uint_parser<> has been instantiated with. If the parsed number overflows this type the parsing fails. Please be aware that the overflow check is not based on the type of the supplied attribute but solely depends on the template parameter T."
the valid input range of `x3::uint_parser<T>` should be `0` - `std::numeric_limits<T>::max()`. However, the current implementation takes values from `std::numeric_limits<T>::max()+1` - `std::numeric_limits<std::make_unsigned_t<T>>::max()` also as valid input when `T` is a signed integral.
Example:
`x3::uint_parser<signed char>` should parse 0-127, but with current implementation 128-255 also works.
Test cases are added.

fix uint_parser<T(signed)> overflow problem

---

include/boost/spirit/home/x3/nonterminal/rule.hpp
include/boost/spirit/home/x3/support/ast/variant.hpp
test/x3/confix.cpp

These workarounds are enough to make X3 pass all the tests on VS2015 (19.00.24210).
I think they are not too awful. Otherwise VS2015 should be banned as unusable.

X3: Workaround VS2015 bugs

---

include/boost/spirit/home/x3/operator/detail/sequence.hpp
include/boost/spirit/home/x3/support/traits/attribute_category.hpp
include/boost/spirit/home/x3/support/traits/is_range.hpp
include/boost/spirit/home/x3/support/traits/move_to.hpp
test/x3/raw.cpp

See https://svn.boost.org/trac10/ticket/12928
```cpp
std::string str("x123x"); 
boost::iterator_range<boost::range_iterator<decltype(str)>::type> attr; 
if( x3::parse( boost::begin(str), boost::end(str), x3::lit('x') >> x3::raw[+x3::digit] >> x3::lit('x'), attr ) ) { 
std::cout<<"Match! attr = "<<attr<<std::endl; 
} else { 
std::cout<<"Not match!"<<std::endl; 
}
```
produces compile error
```
/usr/local/include/boost/spirit/home/x3/support/traits/container_traits.hpp:176:15: error: no member named 'insert' in 'boost::iterator_range<__gnu_cxx::__normal_iterator<char *, std::__cxx11::basic_string<char> > >'
c.insert(c.end(), first, last);
~ ^
```
The iterator_range is no container and must not go to container_traits.

Parse into range

---

include/boost/spirit/home/qi/detail/permute_function.hpp
test/qi/permutation.cpp

Closes https://svn.boost.org/trac10/ticket/12473
Optional parser never fails so `attr = val;` always triggers and initializes
the `attr` value. The special case for optional attributes could be safely
removed as any underlying parser must already correctly handle optionals.

Qi: Permutations parser always initializes optionals

---

include/boost/spirit/home/qi/operator/sequential_or.hpp
include/boost/spirit/home/support/algorithm/any_if_ns_so.hpp
include/boost/spirit/home/support/algorithm/any_ns_so.hpp
include/boost/spirit/include/support_any_if_ns_so.hpp
include/boost/spirit/include/support_any_ns_so.hpp

After two hours of fighting with the optimizer, I happily drew attention to
this little nifty bitwise operator in `any_if_ns` function.
Explanation of the bug: bitwise inclusive OR operator is not a sequence point
(per chapter §5.13 of C++14 standard), that's why at compiling the expression
`a() | b() | ... | z()` optimizer is allowed to rearrange the execution order
of the functions `a`, `b` ... `z`.
There is high chance that a lot of people were misguided by the bug and chose
not to use `sequential_or`.
I vaguely remember how about three years ago I thought that I am dumb and/or
the documentation is wrong when I tried to use the `sequential_or` but ended
with some workaround.
There are three possible fixes:
- This one
- Make the original `any_ns` and `any_if_ns` strict ordered
(could …

sequential_or: Fixed random order execution of underlying parsers

---

include/boost/spirit/home/qi/parse.hpp
include/boost/spirit/home/x3/core/parse.hpp
test/qi/Jamfile
test/qi/iterator_check.cpp
test/x3/Jamfile
test/x3/iterator_check.cpp

The concept of `ForwardIterator` is flawed because it mixed 2 sets of concepts (value access and traversal) into 1 package.
http://www.boost.org/doc/libs/1_65_1/libs/iterator/doc/new-iter-concepts.html
It requires `value_type (const)&` as return type when dereference is applied, which is not mandatory in spirit parsing. A return type which is convertible to value_type is good enough. `ReadableIteratorConcept` and `ForwardTraversalConcept` should be what we need for the iterator check.
For example, the iterator of the range returned by `boost::adaptors::transform(std::string, func)` is normally not a `ForwardIterator`. But it fulfills `ReadableIteratorConcept` and `ForwardTraversalConcept` and should be able to be parsed by spirit.
Test cases are added for both qi and x3. 
There is also a …

ForwardIterator -> ReadableIteratorConcept & ForwardTraversalConcept

---

.appveyor.yml

Mostly the same as #291.
There is no `ccache` on Windows, so I am using `clcache`.
VS2017 build with `/std:c++latest` might be added later.
The build times are disaster.

Add Appveyor-CI

---

classic/test/Jamfile
classic/test/threads_disabled_compile.cpp
include/boost/spirit/home/classic/utility.hpp

Closes https://svn.boost.org/trac10/ticket/12639
Spirit should not include any Boost.Thread header until user explicitly
requested threadsafe support with BOOST_SPIRIT_THREADSAFE defined.

Classic: Fix compilation with BOOST_DISABLE_THREADS defined

---

include/boost/spirit/home/lex/lexer/lexertl/generate_static.hpp

Closes https://svn.boost.org/trac10/ticket/11540.
Actually this should have been caught by `regression_matlib_generate_switch`
test, but it is not complex enough to cover all cases. We do not have the
coverage reports yet, but the fix is trivial so I think it is ok.

Lex: Fixed C2001 'newline in constant' warning in generated lexers

---

include/boost/spirit/home/x3/core/detail/parse_into_container.hpp
test/x3/Jamfile
test/x3/fusion_map.cpp

`build_container<char>` specialization was added in 84c0c075 (#5)

X3: Reenable fusion::map support

---

include/boost/spirit/home/x3/support/traits/move_to.hpp
test/x3/lit1.cpp

This affects lazy attribute constructing parsers, which exposes not an actual
attribute, but a pair of iterators (like `string` or `attr("...")`).

X3: Fixed iterator move_to to single item sequence

---

include/boost/spirit/home/classic/core/primitives/primitives.hpp

Closes https://svn.boost.org/trac10/ticket/7371
The trac ticket author was right and left unnoticed for 5 years.

Classic: Increment scanner through iterator policy

---

include/boost/spirit/home/x3/directive/expect.hpp
test/x3/expect.cpp

So far, a kleene star within a expect directive did not correctly populate the attribute. For example the program
``` cpp
#include <iostream>
#include <boost/spirit/home/x3.hpp>
#include <boost/spirit/home/support/multi_pass.hpp>
namespace x3 = boost::spirit::x3;
namespace ascii = boost::spirit::x3::ascii;
using x3::lit;
using x3::char_;
int main() {
auto const rule
= lit(':')
> *(char_('A', 'Z') | char_('a', 'z'))
;
std::string input(":AaBbCcDd");
std::vector<char> result;
std::cout << "Success: " << parse(input.begin(), input.end(), rule, result) << std::endl;
for (auto& r : result) {
std::cout << r;
}
std::cout << std::endl;
}
```
gives the following results:
- the parser accepts the string, i.e. `parse` returns true
- but the `result` vector only contains the last character of the …

X3: Fix expect directive's handling of container attributes

---

test/lex/token_moretypes.cpp

Simplifies values declaration and fixes warnings.
```
../libs/spirit/test/lex/token_moretypes.cpp:218:30: warning: missing field 'val' initializer [-Wmissing-field-initializers]
../libs/spirit/test/lex/token_moretypes.cpp:219:30: warning: missing field 'val' initializer [-Wmissing-field-initializers]
../libs/spirit/test/lex/token_moretypes.cpp:219:41: warning: missing field 'val' initializer [-Wmissing-field-initializers]
../libs/spirit/test/lex/token_moretypes.cpp:223:17: warning: missing field 'val' initializer [-Wmissing-field-initializers]
../libs/spirit/test/lex/token_moretypes.cpp:223:43: warning: missing field 'val' initializer [-Wmissing-field-initializers]
../libs/spirit/test/lex/token_moretypes.cpp:224:17: warning: missing field 'val' initializer [-Wmissing-field-initializers] …
```

Lex.Tests: token_moretypes: Use optional

---

include/boost/spirit/home/x3/operator/detail/sequence.hpp
include/boost/spirit/home/x3/support/traits/tuple_traits.hpp
test/x3/Jamfile
test/x3/attribute_type_check.cpp

Most of discussion happened in https://github.com/boostorg/spirit/pull/219#issuecomment-352905393.
Brief overall: Currently we do not know what a8e391b was fixing (and it seems partly redundant), but it introduced an unwanted behavior of passing `fusion::iterator_range` to attribute-generating parsers.
This PR reimplements a spirit of a8e391b commit. It tries to pass through as many attributes as
possible. For example: a single item sequences like `fusion::vector<T>` will be passed through,
while fusion iterators, fusion iterator range or view of size one will be dereferenced before passing
to underlying parsers of sequence parser.
TODO:
- Tests? It is not that easy to test, but I can make a custom parser and check attribute type in it.
- Should `tuple_traits.hpp` be renamed? The name …

X3: Dereference a single item view instead of unwrapping sequence

---

classic/test/position_iterator_tests.cpp
include/boost/spirit/home/classic/iterator/multi_pass.hpp
include/boost/spirit/home/karma/stream/ostream_iterator.hpp
include/boost/spirit/home/support/iterators/detail/multi_pass.hpp

Boost's iterator.hpp is deprecated, too. It does nothing but pulling std::iterator into namespace boost and including standard headers 'iterator' and 'cstddef'. Therefore get rid of all of that and replace inheritance by lifting std::iterator's members into the derived class.

Inheriting std::iterator is deprecated in c++17

---

include/boost/spirit/home/x3/core/detail/parse_into_container.hpp

::empty() is called on the Attribute in parse_into_container_impl. If Attribute has no ::empty(), if fails to compile. Probably instead it should use traits::is_empty(...).

X3: Use traits to test if container is empty

---

classic/test/scanner_tests.cpp

.. and in the Dinkum STL shipped with VxWorks it's an inline function.

toupper() may not be a macro

---

include/boost/spirit/home/qi/numeric/detail/real_impl.hpp
include/boost/spirit/home/x3/support/numeric_utils/extract_real.hpp

Should prevent static analyzer false-positives.
Closes #356.

Added some asserts to real parsers

---

doc/Jamfile
doc/spirit2.qbk
doc/x3/include.qbk
repository/doc/karma/confix.qbk
repository/doc/qi/advance.qbk
repository/doc/qi/confix.qbk
repository/doc/qi/distinct.qbk
repository/doc/qi/flush_multi_pass.qbk
repository/doc/qi/keywords.qbk

For some reason boost stopped building docs for 'sublibs' in 1.62. X3 docs were never integrated into build 
system.
Also includes some fixed to Repository doc build errors and versions info adjustments.
Closes #357, [trac 12322](https://svn.boost.org/trac10/ticket/12322).

Include Repository and X3 docs in doc builds

---

include/boost/spirit/home/support/detail/hold_any.hpp

The PR #36 does not fixed problem for C++03 and wide range of MSVC compilers.
Closes [trac 8268](https://svn.boost.org/trac10/ticket/8268).

Added missing copy assignment operator

---

include/boost/spirit/home/karma/numeric/detail/numeric_utils.hpp

When compiling with -fsanitize=undefined, `absolute_value` fails on minimal signed integer values:
```
../../../boost/spirit/home/karma/numeric/detail/numeric_utils.hpp:97:5: runtime error: negation of -9223372036854775808 cannot be represented in type 'long long int'; cast to an unsigned type to negate this value to itself
#0 0x404e9d in boost::spirit::traits::absolute_value<long long, void>::call(long long) ../../../boost/spirit/home/karma/numeric/detail/numeric_utils.hpp:97
#1 0x4343cd in boost::spirit::traits::absolute_value<long long, void>::type boost::spirit::traits::get_absolute_value<long long>(long long) ../../../boost/spirit/home/karma/numeric/detail/numeric_utils.hpp:149
#2 0x42892b in bool boost::spirit::karma::any_int_generator<long long, boost::spirit::unused_type, …
```

Karma: Perform negation in unsigned type to prevent UB

---

include/boost/spirit/home/x3/operator/detail/sequence.hpp
test/x3/sequence.cpp

If underlying parser of sequence is sequence or unary ending down
to a sequence the container attribute should be passed through.
TODO:
- I have a naming problem, hope to receive a feedback.
- I don't like SFINAE, but other solutions will have more boilerplate.
Any suggestions?
Fixes https://svn.boost.org/trac10/ticket/12085

X3: Pass container attribute through sequence

---

include/boost/spirit/home/x3/core/skip_over.hpp

End iterator check is redundant here because it is done in skipper.

X3: skip_over: Remove redundant check

---

include/boost/spirit/home/karma/detail/extract_from.hpp
include/boost/spirit/home/support/adapt_adt_attributes.hpp
test/karma/regression_adapt_adt.cpp

The `extract_from_attribute` returns a reference to a temporary
value produced by calling Fusion ADT adapted sequence getter that
returns by value.
Was reported 6 years ago https://svn.boost.org/trac10/ticket/6126

Karma: Fixed use after scope bug if ADT getter returns by value

---

example/x3/Jamfile
example/x3/calc/calc4b.cpp

I'm not sure whether this is a regression or whether `BOOST_SPIRIT_DEFINE(rule1 = ... , rule2 = ... , ...)` never worked.  At least I have never seen this anywhere else.

Make calc4b actually compile

---

include/boost/spirit/home/x3/support/ast/variant.hpp

This applies the fix in 6d6f40c3e5 to all BOOST_NOEXCEPT_IF statements in variant.hpp. I have trouble compiling a toy project with VS2015, as these noexcept if statements fails to compile.
I saw the support for VS2015 in 6d6f40c3e5, and got really execited so I checked out the develop branch to test it, unfortunately it fails for me to compile a small project that I have here:
https://gitlab.com/RandomInEqualities/Calculator
It compiles with these changes. Is the changes ok to do?

X3: variant: More fixes for compilation with VS2015 Update 3

---

classic/test/traverse_tests.cpp

Should fix the stack overflow error reported by ASAN.

Classic.Tests: traverse_tests: Fixed an off by one error

---

example/qi/reference.cpp
include/boost/spirit/home/support/detail/endian/endian.hpp
test/karma/binary1.cpp
test/karma/binary2.cpp
test/karma/binary3.cpp
test/qi/binary.cpp
test/qi/regression_binary_action.cpp
test/x3/binary.cpp

The `boost/detail/endian.hpp` header is deprecated.

Use endian macros from Predef

---

repository/test/Jamfile

Workaround qi_repo_keywords test fail on MSVC-14.1

---

include/boost/spirit/home/karma/detail/attributes.hpp
include/boost/spirit/home/qi/detail/attributes.hpp
include/boost/spirit/home/support/attributes.hpp
test/qi/regression_adapt_adt.cpp

Domain-wide transforms on the main template produce ambiguity with
user template type partial specializations. To overcome the issue
we hide our domain dispatcher under this intermediate template.
Fixes #396.

V2: Fixed transform_attribute ambiguity

---

include/boost/spirit/home/karma/detail/output_iterator.hpp

With `BOOST_SPIRIT_UNICODE` defined Clang, MinGW and Cygwin were using `wchar_t`.
I have switched to OS detection with `_WIN32`, it will give the right results for most compilers except Cygwin.
Actually buffer char type should not be chosen that way, but it looks like nobody cares.
<details><summary>Error log for search engines</summary>
Clang
-----
```
In file included from regression_unicode_char.cpp:14:
In file included from ./boost/spirit/home/karma/nonterminal/grammar.hpp:18:
In file included from ./boost/spirit/home/karma/nonterminal/rule.hpp:38:
./boost/spirit/home/karma/detail/output_iterator.hpp:225:13: error: static_assert failed "sizeof(T) <= sizeof(buffer_char_type)"
BOOST_STATIC_ASSERT(sizeof(T) <= sizeof(buffer_char_type));
^ …
```

Karma: Fixed wrong buffer char type on Windows

---

include/boost/spirit/home/support/utf8.hpp
include/boost/spirit/home/x3/support/utility/utf8.hpp
test/qi/Jamfile
test/qi/to_utf8.cpp
test/x3/Jamfile
test/x3/to_utf8.cpp

Spirit were assuming that wchar_t is 32-bit and the content is UCS-4.
It is wrong, the actual representation is implementation defined [lex.ccon]/6.
However, on most Unix platforms this assumption is valid and gives the
expected outcome, but on Windows wchar_t is 16-bit and the content is UTF-16.
Fixes #395.

to_utf8: Fixed wchar_t handling on Windows

---

include/boost/spirit/home/lex/lexer/lexer.hpp

When `min_token_id` is not a valid value for `id_type` and `first_id` is not provided lexer constructor is triggering UB. To fix this problem, constructor with ommited `first_id` initializes `next_token_id` directly, so if unique ids feature is not used there is no UB.
Found the problem in [a lex test](https://github.com/boostorg/spirit/blob/develop/test/lex/regression_wide.cpp) with UBSan.
```
boost/spirit/home/lex/lexer/lexer.hpp:382:27: runtime error: load of value 65536, which is not a valid value for type 'boost::spirit::lex::lexer<boost::spirit::lex::lexertl::actor_lexer<boost::spirit::lex::lexertl::token<__gnu_cxx::__normal_iterator<wchar_t *, std::__cxx11::basic_string<wchar_t> >, boost::mpl::vector<wchar_t, std::__cxx11::basic_string<wchar_t>, double, mpl_::na, mpl_::na, …
```

Lex: Avoid casting `min_token_id` to `id_type` in lexer ctor

---

classic/test/position_iterator_tests.cpp
include/boost/spirit/home/classic/iterator/impl/position_iterator.ipp

When underlying iterator returns by value the corresponding position_iterator was providing iterator_adaptor with a reference type what lead to returning a reference to a local variable in dereference operator.
Made a custom trait because it is a way more elegant than:
```cpp
typedef typename boost::mpl::if_c<
boost::is_reference<reference>::value,
typename boost::add_reference<
typename boost::add_const<
typename boost::remove_reference<reference>::type
>::type
>::type,
typename boost::add_const<reference>::type
>::type const_reference_type;
```
Fixes https://svn.boost.org/trac10/ticket/9737.

Classic: Fixed position_iterator forming reference to local

---

include/boost/spirit/home/x3/support/numeric_utils/detail/extract_int.hpp

It is a symmetrical change to Qi one that landed a while ago d8637825 (#146).
There should not be race condition on C++11+, but MSVC still does not do compile-time initialization of static variables when constructor is constexpr https://developercommunity.visualstudio.com/content/problem/336946/class-with-constexpr-constructor-not-using-static.html

X3: Use constexpr in numeric utils instead of static storage

---

include/boost/spirit/home/support/utree/detail/utree_detail2.hpp

Result of shifting a negative value is an implementation defined behavior.
UBSan output:
```
boost/spirit/home/support/utree/detail/utree_detail2.hpp:47:48: runtime error: left shift of negative value -128
#0 0x45cc72 in boost::spirit::detail::fast_string::tag() const ~/boost-root/./boost/spirit/home/support/utree/detail/utree_detail2.hpp:47:48
#1 0x45c94c in boost::spirit::utree::copy(boost::spirit::utree const&) ~/boost-root/./boost/spirit/home/support/utree/detail/utree_detail2.hpp:1502:31
#2 0x440cc7 in boost::spirit::utree::operator=(boost::spirit::utree const&) ~/boost-root/./boost/spirit/home/support/utree/detail/utree_detail2.hpp:848:13
#3 0x43ce6f in main ~/boost-root/libs/spirit/test/support/utree.cpp:492:16
#4 0x7f5d472bc2e0 in __libc_start_main …
```

utree: Fixed negative value shift

---

include/boost/spirit/home/qi/nonterminal/rule.hpp

It looks like mismatching skipper types and `parse`/`phrase_parse` calls are
quite popular mistakes, and the actual problem is not clear for users despite
that there is a comment near the call that will fail and the hint should be
found by following to the file and line that compiler reports the error on.
Closes #426.

Qi: rule: Added asserts for mismatching skipper types

---

include/boost/spirit/home/qi/numeric/detail/numeric_utils.hpp
include/boost/spirit/home/support/numeric_traits.hpp
include/boost/spirit/home/x3/support/numeric_utils/detail/extract_int.hpp
include/boost/spirit/home/x3/support/traits/numeric_traits.hpp
test/qi/Jamfile
test/qi/extract_int.cpp
test/x3/Jamfile
test/x3/extract_int.cpp

It will allow to test `extract_int` properly.
Changed default `check_overflow` trait implementation to be `is_bounded`
as it also covers float types and user data types.
Replacing `boost::integer_traits` with `std::numeric_limits` will not hurt
performance because even MSVC 9/GCC 4.1/Clang 3.0 folds `min`/`max` calls
to a constant at compile time and since C++11 they are even constexpr.

extract_int: Custom integers support

---

include/boost/spirit/home/qi/detail/alternative_function.hpp
include/boost/spirit/home/x3/support/traits/variant_find_substitute.hpp
include/boost/spirit/home/x3/support/traits/variant_has_substitute.hpp

From `mpl::find` docs:
> `typedef find<s,t>::type i;`
> Semantics: Equivalent to `typedef find_if<s, is_same<_,t> >::type i;`

Replace mpl::find_if+is_same with find

---

include/boost/spirit/home/x3/nonterminal/rule.hpp
test/x3/Jamfile
test/x3/rule1.cpp
test/x3/rule_separate_tu.cpp
test/x3/rule_separate_tu_grammar.cpp
test/x3/rule_separate_tu_grammar.hpp

When a rule has no attribute (leaves `Attribute` template parameter as default)
the `BOOST_SPIRIT_INSTANTIATE` macro instantiates a `parse_rule` helper function
with a wrong signature because `parse`, `phrase_parse`, and `skip_over` pass as
the attribute `unused` variable which deduces to `unused_type const&` type, but
`BOOST_SPIRIT_INSTANTIATE` instantiates `parse_rule` with `unused_type&` type.
Used a trick to change `parse_rule` signature to take unsued_type by value when rule has no attribute (the signature `parse_rule(..., unsued_type)`).

X3: Fixed wrong parse_rule signature instantiation

---

include/boost/spirit/home/x3/nonterminal/detail/rule.hpp
test/x3/rule3.cpp

There is a mistake in `make_attribute` trait that leads to synthesization and
immediately throwing out an attribue, so rule context always was unused_type
when actual attribute is unused_type (added test for this case). Instead of
fixing `make_attribute` trait I just completely removed synthesization in
rule by removing `make_attribute` trait usage (the traits could be removed
after a simple change in 'action' parser). I think the change is better
than fixing the trait because it removes excessive attribute default
construction in every rule and makes rule almost free to use.

X3: rule: Skip attribute synthesization on unused actual attribute

---

include/boost/spirit/home/x3/nonterminal/rule.hpp
test/x3/rule_separate_tu.cpp
test/x3/rule_separate_tu_grammar.cpp
test/x3/rule_separate_tu_grammar.hpp

During overload resolution disallowed signature can be instantiated leading to firing the static assertation and overload resolution failure. I could just remove it, but do not want to leave unbounded by value overloads; replacing to not deducing Attribute with specifying a default parameter will not work because we want to allow `BOOST_SPIRIT_DECLARE` without prior `BOOST_SPIRIT_DEFINE` - this requires having default parameters in both declaration and definition and the standard seems to forbid it (GCC - fine, MSVC - warning, Clang - error).
Reverts #437, fixes #453.

X3: Fixed static assert on parse_rule instantiation

---

include/boost/spirit/home/x3/nonterminal/rule.hpp
test/x3/rule3.cpp
test/x3/rule_separate_tu.cpp

This will deal with linking problems when rule attribute type is not the same
as the actual attribute type. It will not harm anyone as the transformation
after parse_rule will just pass-through the attribute because it will be the
same there. It will also do not alter rule_definition parsing so other usages
are still valid.
Refs #454, supersedes #347.

X3: Perform attribute transformation before calling parse_rule

---

doc/x3/tutorial/minimal.qbk
doc/x3/tutorial/roman.qbk
include/boost/spirit/home/x3/nonterminal/rule.hpp

After #456 `parse_rule` is always called with value of `rule::attribute_type&`
type. By removing attribute type deduction we also will turn any possible bug
in `transform_attribute` from a linkage to compile error.
Fixes #454

X3: parse_rule attribute must always be of rule::attribute_type&

---

doc/qi/numeric.qbk
include/boost/spirit/home/qi/numeric/detail/real_impl.hpp
include/boost/spirit/home/qi/numeric/real_policies.hpp
include/boost/spirit/home/x3/numeric/real_policies.hpp
include/boost/spirit/home/x3/support/numeric_utils/extract_real.hpp
test/qi/real.hpp
test/x3/real.hpp

It was poorly documented and never worked correctly. None of atof, strtof, and
input streams are accepting such values. Fixing it would be a bigger breaking
change than removing it.
Fixes #415, addresses #163 and https://svn.boost.org/trac10/ticket/8699

Remove broken 1.0#INF parser

---

include/boost/spirit/home/support/utree/utree_traits.hpp

The double conversion `spirit::string -> std::string -> spirit::string` was
happening silently in rules because of `transform_attribute` was returning
`std::string` and implicit constructor in `spirit::string`.
The mistake could be prevented if `spirit::basic_string` constructor from
derived class was explicit, but `utree_cast` uses `is_convertible` while
`is_constructible` is not implemented for C++03 (it is possible, but requires
expression SFINAE support from compiler - N2634).

utree: Fixed double conversion

---

include/boost/spirit/home/karma/action/action.hpp
include/boost/spirit/home/karma/detail/attributes.hpp
include/boost/spirit/home/karma/nonterminal/rule.hpp
include/boost/spirit/home/qi/action/action.hpp
include/boost/spirit/home/qi/detail/attributes.hpp
include/boost/spirit/home/qi/nonterminal/rule.hpp
include/boost/spirit/home/support/attributes.hpp
include/boost/spirit/repository/home/karma/nonterminal/subrule.hpp
include/boost/spirit/repository/home/qi/nonterminal/subrule.hpp

This will allow to simplify transform_attribute (e.g. no need to handle
references anymore) and to ensure the pre/post/fail calls are made to the
same transformation.
That's what I mentioned in https://github.com/boostorg/spirit/pull/460#issuecomment-462967855

V2: Merge make_attribute into transform_attribute

---

include/boost/spirit/home/karma/action/action.hpp
include/boost/spirit/home/karma/nonterminal/rule.hpp
include/boost/spirit/home/qi/action/action.hpp
include/boost/spirit/home/qi/auxiliary/attr_cast.hpp
include/boost/spirit/home/qi/detail/attributes.hpp
include/boost/spirit/home/qi/nonterminal/rule.hpp
include/boost/spirit/home/support/attributes.hpp
include/boost/spirit/home/support/attributes_fwd.hpp
include/boost/spirit/repository/home/karma/nonterminal/subrule.hpp
include/boost/spirit/repository/home/qi/nonterminal/subrule.hpp

This will ensure that the same transformation is used for all operations.
Followup to #464

V2: Use pre/post/fail functions directly from the transform

---

include/boost/spirit/home/qi/numeric/detail/numeric_utils.hpp
include/boost/spirit/home/x3/support/numeric_utils/detail/extract_int.hpp
test/qi/extract_int.cpp

The IgnoreOverflowDigits=true parser always succeeds and because of that it
expects from the digits parser that a number passed as inout argument will be
changed only on success.
Changed negative_accumulator and X3 for consistency.
Fixes #428

extract_uint: Fixed IgnoreOverflowDigits=true problem at overflow

---

include/boost/spirit/home/x3/core/detail/parse_into_container.hpp
include/boost/spirit/home/x3/operator/detail/sequence.hpp
include/boost/spirit/home/x3/operator/optional.hpp
include/boost/spirit/home/x3/support/traits/container_traits.hpp
test/x3/container_support.cpp
test/x3/kleene.cpp
test/x3/list.cpp
test/x3/optional.cpp
test/x3/plus.cpp
test/x3/repeat.cpp
test/x3/sequence.cpp
test/x3/utils.hpp

X3: Improve situation with move only types

---

.travis.yml
test/karma/case_handling1.cpp
test/karma/case_handling2.cpp
test/karma/case_handling3.cpp
test/karma/char_class.cpp
test/karma/encoding.cpp
test/karma/pattern4.cpp
test/qi/char_class.cpp
test/qi/encoding.cpp
test/qi/no_case.cpp
test/qi/rule1.cpp
test/qi/rule2.cpp
test/qi/rule3.cpp
test/qi/rule4.cpp
test/x3/any_parser.cpp
test/x3/char_class.cpp
test/x3/no_case.cpp
test/x3/rule1.cpp
test/x3/rule2.cpp
test/x3/rule3.cpp
test/x3/rule4.cpp

Mostly to please Clang, but also makes sources UTF-8 valid.

Hexencode extended ASCII

---

include/boost/spirit/home/x3/support/utility/testing.hpp

Spotted this because of unused parameters warning.

X3: support/utility/testing.hpp: Propagate prefix and suffix [skip ci]

---

include/boost/spirit/home/support/detail/endian/endian.hpp

- Fixed macro redefinition:
- `BOOST_MINIMAL_INTEGER_COVER_OPERATORS`
- `BOOST_NO_IO_COVER_OPERATORS`
- `BOOST_SPIRIT_ENDIAN_NO_CTORS`
- `BOOST_SPIRIT_ENDIAN_DEFAULT_CONSTRUCT`
- Undef internal macros.
- Fixed-width integer detection.
Closes #348

Support: Endian problems

---

include/boost/spirit/home/karma/detail/attributes.hpp
include/boost/spirit/home/qi/detail/attributes.hpp
include/boost/spirit/home/support/attributes.hpp
include/boost/spirit/home/x3/nonterminal/detail/transform_attribute.hpp

The special handling was used instead of removing references from the `make_attribute<T,U>::type`. Since `make_attribute` is gone the workaround is no longer needed.
Closes #450

transform_attribute: Disallow references as template parameters

---

classic/test/file_iterator_tests.cpp

We have multiple runs of the test and sometimes it fails because of a race.

Classic: file_iterator_tests: Fixed temp file race

---

include/boost/spirit/home/lex/lexer/lexertl/functor_data.hpp

Fixes a GCC -Wuninitialized warning in lex/regression_syntax_error which is
most likely a false positive https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89733
```cpp
gcc.compile.c++ ../../../../bin.v2/libs/spirit/test/lex/lex_regression_syntax_error.test/gcc-8/release/cxxstd-2a-iso/threading-multi/visibility-hidden/regression_syntax_error.o
In file included from ../../../../boost/spirit/home/lex/lexer/lexertl/lexer.hpp:22,
from ../../../../boost/spirit/home/lex/lexer_lexertl.hpp:16,
from ../../../../boost/spirit/include/lex_lexertl.hpp:16,
from regression_syntax_error.cpp:10:
../../../../boost/spirit/home/lex/lexer/lexertl/functor_data.hpp: In function ‘bool boost::spirit::lex::tokenize_and_parse(Iterator&, Iterator, const Lexer&, const ParserExpr&) [with Iterator = const char*; Lexer = …
```

lexertl: Missing member initialization

---

doc/lex/lexer_api.qbk
include/boost/spirit/home/lex/tokenize_and_parse_attr.hpp

They were added 10 years ago and did not compile all the time due to bugs spotted during warning elimination work, but the main reason to remove them is that there was not a single report about the issues.
Closes #490

Lex: Remove variadic `tokenize_and_phrase_parse`

---

classic/doc/functional.html
classic/doc/preface.html
classic/doc/references.html
classic/phoenix/doc/polymorphic_functions.html
classic/phoenix/doc/preface.html
classic/phoenix/doc/quick_start.html
classic/phoenix/doc/references.html
doc/references.qbk
doc/spirit2.qbk
repository/doc/spirit2_repository.qbk

Hi, this PR fixes a couple for broken links. I did my best to ensure that they refer to the same information as the original links (using the web archive). Some modified files (like classic/phoenix/doc/preface.html) state that they are generated at the top but I failed to find the corresponding source files for their generation in the repository, so I modified them anyway.

Replace a couple of dead links.

---

include/boost/spirit/home/x3/char/char_set.hpp
include/boost/spirit/home/x3/support/traits/string_traits.hpp

We probably may completely remove `string_traits.hpp` by rewriting things further.

X3: Simplify string_traits

---

test/x3/char1.cpp
test/x3/test.hpp

This pull request gives X3 Unicode literal support for its `char_set<boost::spirit::char_encoding::unicode>`. This passively enables `boost::spirit::x3::unicode::char_` to now support string literals such as: `U"hello, \u20ac!"`.
This PR also extends the X3 `test` utility to work with `boost::basic_string_view` as well.

Unicode charset

---

include/boost/spirit/home/support/detail/hold_any.hpp

boost/detail/sp_typeinfo.hpp is deprecated, use boost/core/typeinfo.hpp instead.

Port to Boost.Core typeinfo.hpp to avoid deprecated warnings

---

include/boost/spirit/home/x3/char/any_char.hpp

The following assert fails:
int main() {
namespace x3 = boost::spirit::x3;
char const* input = "\x80";
assert(!x3::parse(input, input+1, x3::ascii::char_));
}
The assert should pass because char_encoding::ascii::test disallows
non-7bit ASCII, so "\x80" is outside the encoding.
The corresponding Qi test case DOES pass:
int main() {
namespace qi = boost::spirit::qi;
char const* input = "\x80";
assert(!qi::parse(input, input+1, qi::ascii::char_));
}
This simple fix requires the encoding's `ischar` to return true always,
making the behavior as specified and consistent with Qi and docs.

Fix for #520 any_char accepts outside encoding

---

include/boost/spirit/home/x3/char/unicode.hpp
test/x3/char_class.cpp
test/x3/test.hpp

Fixes https://github.com/boostorg/spirit/issues/524
Due to a bug in the condition evaluated by:
`((sizeof(Char) <= sizeof(char_type)) || encoding::ischar(ch))`
invalid Unicode literals would test `true` which is erroneous and when used with `x3::unicode::alpha` would create an out-of-bounds access in the `category_lookup(::boost::uint32_t ch)` function.

Unicode out-of-bounds category lookup fixes

---

include/boost/spirit/home/x3/support/no_case.hpp

MSVC barfs on implicit conversion to `bool` here, and it is indeed suspicious.
I have no idea why `in_set` return type is a char type, the method name itself suggests that it returns boolean value. The only used template parameter type seems to be `basic_set` and its `test` method return `bool`. https://github.com/boostorg/spirit/blob/9cf7a3ef739d57d091ed3812a54481cc877b0a56/include/boost/spirit/home/support/char_set/basic_chset.hpp#L35-L39
The usages of `in_set` method also seem to expect a boolean value from it. https://github.com/boostorg/spirit/blob/9cf7a3ef739d57d091ed3812a54481cc877b0a56/include/boost/spirit/home/x3/char/char_set.hpp#L99

X3: Remove bool->char->bool conversion

---

include/boost/spirit/home/support/char_encoding/standard.hpp
include/boost/spirit/home/support/char_encoding/standard_wide.hpp

This fixes a regression introduced by 5a217a5e033d34b016fef41ee95e311bc1a24140.

Add missing includes of assert.hpp

---

include/boost/spirit/home/x3/nonterminal/detail/rule.hpp
test/x3/rule_separate_tu.cpp

Regressed in #457.
Fixes #548.

X3: Fix `parse_rule` definition check

---

include/boost/spirit/home/x3/support/unused.hpp
test/x3/unused_type.cpp

The `unused_type` has an implicit constructor from any type, because of that
ADL can find and match its streaming operator for any type. Removing they from namespace scope fixes #552.

X3: Hide `unused_type` streaming operators

---

include/boost/spirit/home/karma/nonterminal/rule.hpp
include/boost/spirit/home/qi/nonterminal/rule.hpp
include/boost/spirit/home/x3/nonterminal/rule.hpp
include/boost/spirit/repository/home/karma/nonterminal/subrule.hpp
include/boost/spirit/repository/home/qi/nonterminal/subrule.hpp

```cpp
qi::rule<char const*, int()>        // ok
qi::rule<char const*, int const()>  // ok, but strange
qi::rule<char const*, int&()>       // meaningless reference
qi::rule<char const*, int const&()> // meaningless reference
ka::rule<char const*, int()>        // ok
ka::rule<char const*, int const()>  // meaningless const
ka::rule<char const*, int&()>       // meaningless reference
ka::rule<char const*, int const&()> // meaningless const and reference
```

Added static assertion for meaningless rule attribute qualifiers

---

include/boost/spirit/home/karma/detail/output_iterator.hpp
include/boost/spirit/home/support/utf8.hpp
include/boost/spirit/home/x3/support/utility/utf8.hpp
test/qi/to_utf8.cpp
test/x3/to_utf8.cpp

Upon upgrading to from 1.67.0 to boost 1.72.0, I just discovered #413 has broken builds for us, albiet on a fairly exotic platform (using spirit::qi in a [winelib](https://wiki.winehq.org/Winelib) project)
---
Win32 only defines the types from wtypes.h, like WCHAR, LPWCSTR, etc.
These may or may not be the same thing as wchar_t.
MinGW, cygwin, and wineg++ all support `-f(no-)short-wchar`,
with the caveat that libstdc++ must be compiled with the same option.
Doing so is quite unusual for MinGW or cygwin, but more common for wineg++
as it enables building a winelib app with system glibc/libstdc++.
Win32's WCHAR is then unsigned short, or with C++11 perhaps char16_t.
MSVC does explicitly document that its wchar_t is always UTF16:
https://docs.microsoft.com/en-us/cpp/cpp/char-wchar-t-char16-t- …

_WIN32 does not always imply wchar_t is UTF-16

---

include/boost/spirit/home/x3/core/parser.hpp
include/boost/spirit/home/x3/nonterminal/rule.hpp

The previous check was done in a very intrusive way, it also was not catching
the issue when a parser is not inherited from `unary_parser`/`binary_parser`.

X3: Alternate rule placeholder static initialization fiasco check

---

include/boost/spirit/home/qi/detail/parse_auto.hpp
test/qi/Jamfile
test/qi/auto.cpp

The specializations replace literal char parsers with auto parser that does
not perform attribute matching.

Qi: Removed interfering specializations from including auto

---

classic/test/escape_char_parser_tests.cpp

On ARM `ULONG_MAX == WCHAR_MAX`. Fixes #582

Classic.Tests: escape_char_parser_tests: Avoid overflow

---

doc/qi/numeric.qbk
example/karma/complex_number_adapt.cpp
example/karma/complex_number_easier.cpp

Bring qi's `RealPolicies` valid expressions section in line with example
- qi's `parse_frac_n` requires four arguments, not three
Bring karma tutorial `complex` example code in line with discussion below
- Discussed code line examples beneath two `complex` examples differed from the full code snippet above (last `omit[double_]` is omitted there because it's redundant, but to me it felt confusing for it to be missing there and appearing in the discussion later without an explanation)

Small documentation improvements

---

classic/test/grammar_tests.cpp
include/boost/spirit/home/classic/core/non_terminal/impl/rule.ipp
include/boost/spirit/home/classic/phoenix/tuples.hpp

We have had a hard error for `__BORLANDC__ <= 0x570` for a long time to safely remove workarounds for these versions.

Classic: Remove workarounds for unsupported Borland versions

---

include/boost/spirit/home/x3/support/utility/error_reporting.hpp
test/x3/Jamfile

The `path(string).generic_string()` is effectively a no-op.

Cease dependence on Filesystem

---

include/boost/spirit/home/support/detail/scoped_enum_emulation.hpp

`boost/detail/scoped_enum_emulation.hpp` is deprecated in favor of `boost/core/scoped_enum.hpp` and generates warnings. It will be removed in a future release.

Avoid using deprecated header to silence compiler warnings

---

include/boost/spirit/home/classic/core/non_terminal/impl/grammar.ipp
include/boost/spirit/home/classic/core/non_terminal/impl/object_with_id.ipp
include/boost/spirit/home/classic/core/non_terminal/impl/rule.ipp
include/boost/spirit/home/classic/iterator/fixed_size_queue.hpp
include/boost/spirit/home/classic/iterator/multi_pass.hpp
include/boost/spirit/home/classic/iterator/position_iterator.hpp
include/boost/spirit/home/qi/detail/expectation_failure.hpp
include/boost/spirit/home/support/detail/hold_any.hpp
include/boost/spirit/home/support/info.hpp
include/boost/spirit/home/support/iterators/detail/buf_id_check_policy.hpp

Use BOOST_OVERRIDE to fix GCC -Wsuggest-override and Clang-tidy modernize-use-override warnings.
Also fix Clang-tidy readability-container-size-empty and modernize-redundant-void-arg warnings.
Alphabetical order of STL headers.
Closes #587

Use BOOST_OVERRIDE

---

include/boost/spirit/home/x3/operator/detail/alternative.hpp
test/x3/alternative.cpp

Alternative parser were appending empty values with attributeless parsers, while it should not append anything at all.
A container parser of alternative parser of container parser with container of variant of container attribute was failing to compile.
It would be cleaner to simply store every subparser wrapped inside `alternative` because even the general way to call subparsers is via `parse_alternative`, but it will hurt parser expression tree readability.
Fixes #603
Fixes #394

X3: Corner cases in alternative parser with container attribute

---

include/boost/spirit/home/x3/support/traits/container_traits.hpp
test/x3/container_support.cpp

Every sane container implementation will make preallocation if possible, calling `reserve` ourselves increases code size and creates a dead branch inside `insert` which cannot be removed by compiler.
`vector<T>::insert` of major standard library implementations:
- https://github.com/gcc-mirror/gcc/blob/2e0303d60a97ddfcdd8340184bb5dc45e0433327/libstdc%2B%2B-v3/include/bits/vector.tcc#L679
- https://github.com/llvm/llvm-project/blob/fd3295fb6f981a5c030d7540b9eda67f9c723e0f/libcxx/include/vector#L1984
- https://github.com/microsoft/STL/blob/7447ad59d61f50c13861878f340d051c298458df/stl/inc/vector#L911
codegen comparison: https://godbolt.org/z/xJe3jr
single allocation proof: https://godbolt.org/z/bXUyKG

X3: Remove unneeded reserve before insert

---

.travis.yml
include/boost/spirit/home/support/char_encoding/standard_wide.hpp
test/support/Jamfile
test/support/char_encoding.cpp

> For all functions described in this subclause that accept an argument of type wint_t, the value shall
> be representable as a wchar_t or shall equal the value of the macro WEOF. If this argument has any
> other value, the behavior is undefined.
There is no way to produce a `wint_t` value non-representable as `wchar_t` with `std::char_traits<wchar_t>::to_int_type`.
Closes #616

standard_wide: Remove redundant asserts

---

include/boost/spirit/repository/home/qi/directive/distinct.hpp

Like on similar directives, propagate the info from the subject parser
for improved debug/diagnostics.
The idea taken from and demonstrated here: https://stackoverflow.com/questions/65087474/how-to-get-boost-spirit-build-in-error-message-distinct-possible-symbols/65098082#65098082
With this change, user won't need to tediously create a custom `my_distinct` directive just to override the `what()` behaviour.

Improve what() info for distinct directive

---

include/boost/spirit/home/support/char_class.hpp
test/qi/char_class.cpp

I'm getting an assertion failure in boost::spirit using boost 1.74.0:
```
boost/spirit/home/support/char_encoding/standard.hpp:59: static bool boost::spirit::char_encoding::standard::isalnum(int): Assertion `strict_ischar(ch)' failed.
```
This is being called from `boost::spirit::char_class::classify<boost::spirit::char_encoding::standard>::is<unsigned int>()`.
Comparing that function with the functions in `home/x3/support/no_case.hpp`, the wrong type is being used in the cast.

Cast to correct char type to avoid assertion failure

---

test/x3/omit.cpp
test/x3/raw.cpp

Sanity checks to ensure `omit[]` and `raw[]` behave as expected with rules, as requested in #511.
Tested against 1.73.0 (pass) and 1.70.0 (fails due to regression). Not tested against develop/master.

Test omit and raw directives behavior with rules

---

include/boost/spirit/home/support/char_encoding/unicode.hpp
include/boost/spirit/home/support/char_set/range_functions.hpp
include/boost/spirit/home/x3/support/traits/print_attribute.hpp
include/boost/spirit/home/x3/support/traits/print_token.hpp
test/x3/symbols3.cpp

Allows to use a `symbols_parser` with unicode encoding.

Use char32_t as unicode encoding char_type

---

include/boost/spirit/home/support/algorithm/any_if_ns_so.hpp
include/boost/spirit/home/support/char_encoding/standard.hpp
include/boost/spirit/home/x3/string/detail/tst.hpp
include/boost/spirit/home/x3/string/tst.hpp
include/boost/spirit/home/x3/support/traits/print_token.hpp

This patch makes the headers able to be built standalone, making possible C++ clang modules builds. 
@vgvassilev

Add missing includes

---

test/x3/attr.cpp

Fix 379413a50c93539aa432fa9f9fc94fec1d6aa60d did not add a regression test.
For the first time I thought it fixes `vector<std::string, std::string>`, but it run smooth after reverting and it got me some minutes to come up with the test you see in this commit.
@djowel I hope it is what you meant in the commit message and I did not find other bonded regression.

X3.Tests: Added regression test for 379413a5 fix

---

classic/meta/libraries.json
meta/libraries.json
repository/meta/libraries.json

The "cxxstd" json field is being added to each Boost library's meta json information for libraries in order to specify the minumum C++ standard compilation level. The value of this field matches one of the values for 'cxxstd' in Boost.Build. The purpose of doing this is to provide information for the Boost website documentation for each library which will specify the minimum C++ standard compilation that an end-user must employ in order to use the particular library. This will aid end-users who want to know if they can successfully use a Boost library based on their C++ compiler's  compilation level, without having to search the library's documentation to find this out.

[skip ci] Add "cxxstd" json field

---

include/boost/spirit/home/x3/nonterminal/rule.hpp

Not all of our parsers are constexpr constructible, and static local variable is not free for these.
Also, closes #643.

parse_rule: skip rule definition binder creation

---

include/boost/spirit/home/karma/numeric/detail/real_utils.hpp
include/boost/spirit/home/karma/numeric/real_policies.hpp

Users should be able to decide how much they want to print.
Especially since this implementation does not care about significant digits, which hinders unique serialization when using fixed notation with leading zeros.
AFAIK digits10 and max_digits10 are about the **significant** digits, not the digits in the fractional part.
And for serialization and a string-float-string round-trip you should actually at least allow max_digits10 instead of digits10.
Closes #585

Karma: Do not limit precision of real_inserter

---

include/boost/spirit/home/x3/nonterminal/detail/rule.hpp
include/boost/spirit/home/x3/nonterminal/rule.hpp
test/x3/rule_separate_tu_grammar.hpp

Switched `parse_rule` to dispatch only on the rule id only instead.

X3: Fix multiple times missed force_attribute parameter

---

include/boost/spirit/home/x3/nonterminal/detail/rule.hpp
include/boost/spirit/home/x3/nonterminal/rule.hpp
test/x3/rule2.cpp

When a rule placeholder constructed and immediately consumed it cannot be used recursively, that's why the rule definition injection into a parser context can be skipped.
This optimization has a huge impact on compile times because immediate rules are commonly used to cast an attribute like `as`/`attr_cast` does in Qi.
Closes #647

X3: Skip rule definition injection into context

---

include/boost/spirit/home/x3/operator/list.hpp
test/x3/list.cpp

List parser has an attribute only when its subject has (left operand of %).

X3: Fix list parser's has_attribute

---

include/boost/spirit/home/x3/operator/optional.hpp
test/x3/sequence.cpp

Removes flat sequence parser through optional to fix:
* Non-flat `tuple<..., optional<tuple<...>>, ...>` parsing.
* Optional container parsing when it is a part of the sequence and the optional parser subject is a sequence too.
The removed test cases are invalid (see #664) variants of flat through optional. There are a valid ones (like `int_ >> -(int_ >> int_)` into `tuple<int, optional<int>, optional<int>>`) that would be broken after the change, but at the moment I do not have a popper way to make it work.
Fixes #519

X3: Optional parser is not a passthrough parser

---

include/boost/spirit/home/x3/support/utility/error_reporting.hpp
test/x3/error_handler.cpp

When the first line of input would be an empty line, `error_handler` would
fail to properly report an error due to a bug in `get_line_start` method.
Corner case check has been added to fix this.
Example:
```
std::string input = R"(
var x int = 1 ** 2; 
)";
```
Expected:
```
In line 2:
Error! Expecting primary_expression here:
var x int = 1 ** 2;
______________________^_
```
Produced:
```
In line 2:
Error! Expecting primary_expression here:
^_
```

X3: Fix error_handler::get_line_start

---

include/boost/spirit/home/x3/support/utility/error_reporting.hpp
test/x3/error_handler.cpp

A skipper does this already and Spirit usually does not roll back skipper work. When there is no skipper, skipping whitespaces is absolutely wrong thing to do. For example, an error points to an end of the word where an additional input is expected, but there are whitespaces after it.
The `skip_whitespace`/`skip_non_whitespace` were removed since they are not used anymore, and because they are also could trigger UB on a particular input due to unsafe `std::isspace` usage.
Fixes #546.

X3: error_handler should not skip whitespaces

---

example/x3/rexpr/rexpr_full/test/parse_rexpr_test.cpp
example/x3/rexpr/rexpr_full/test/testing.hpp
include/boost/spirit/home/x3/nonterminal/detail/rule.hpp
test/x3/error_handler.cpp

Removes inconsistency when a parser part is factorized into a rule.
Fixes regression introduced in #670.

X3: Remove forced iterator rollback in rule

---

CMakeLists.txt
include/boost/spirit/home/karma/detail/string_generate.hpp
include/boost/spirit/home/lex/lexer/lexertl/lexer.hpp
include/boost/spirit/home/qi/string/tst_map.hpp
include/boost/spirit/home/support/info.hpp
include/boost/spirit/home/support/utf8.hpp
include/boost/spirit/repository/home/qi/operator/keywords.hpp
test/karma/test.hpp
test/lex/set_token_value.cpp
test/lex/token_iterpair.cpp
test/lex/token_moretypes.cpp
test/lex/token_omit.cpp
test/lex/token_onetype.cpp

I have not touch examples because they are not affecting Spirit usage and testing dependencies, and modernizing them also seems like a waste of time when we encourage to start new projects with X3 instead of Qi.

Cease dependence on Foreach

---

include/boost/spirit/home/support/char_set/range_functions.hpp

On Windows/MSVC, the following codes will repro error C2589:
```cpp
#include <boost/regex.hpp>
#include <boost/spirit/include/phoenix_bind.hpp>
#include <boost/spirit/include/phoenix_operator.hpp>
#include <boost/spirit/include/qi.hpp>
int main() {}
```

Prevent error C2589 when min, max was defined.

---

include/boost/spirit/home/karma/numeric/detail/real_utils.hpp
test/karma/real1.cpp

This fixes issue #688. There's some code that divides the integer part
by 10 and increases dim to compensate for it. This code is not
applicable to fixed notation, however, since dim is disregarded in that
case, causing the result to be off by a factor 10.
We can fix this by checking if we're not using fixed notation first,
before doing the division.
Added a few tests to check for this regression.

Karma: fix off by factor 10 error when rounding to integer

---

.appveyor.yml
.github/workflows/ci.yml
.travis.yml
README.md
doc/x3/spirit_x3.qbk
include/boost/spirit/home/x3.hpp

I plan to keep the warning for two releases before starting to utilize C++17 features.
Since Boost 1.81 (scheduled to November 2022) supported compilers will be:
* Clang 4 (currently 3.6)
* GCC 7 (currently 5)
* VS 2017 (currently 2015)

X3: Warn about future C++17 requirement

---

include/boost/spirit/home/x3/nonterminal/detail/rule.hpp
test/x3/rule4.cpp

Instead of usual `[current, end)` pair it receives `[before, current)` pair.
Fixes https://github.com/boostorg/spirit/issues/703#issuecomment-1011021773

X3: Fix `on_success` dispatcher inverted iterator const/mutability

---

doc/x3/tutorial/annotation.qbk
include/boost/spirit/home/x3/nonterminal/detail/rule.hpp
test/x3/rule4.cpp

Reverts the wrong part of #686. Fixes a half of #712 (`positions.position_of()`/`annotation.cpp` example part).

X3: Return back iterator pre-skipping for `on_success` handler

---

include/boost/spirit/home/x3/support/utility/annotate_on_success.hpp

- disable the generic version of on_success if traits::is_variant<T> is true
- specialize on_success for forward_ast<T>, and call on_success() with the result of ast.get()
Fixes #723

Fix: annotate_on_success doesn't annotate variant

---

include/boost/spirit/home/support/iterators/line_pos_iterator.hpp
test/support/line_pos_iterator.cpp

line_pos_iterator now detecs underlying bidirectional iterator and uses iterator-tag dispatching to select appropriate implementations of get_line_start (for bidirectional-iterators: linear-complexity in line-length).
Breaking change: all functions now return underlying iterators instead of line_pos_iterators. But, since they are only used to get the bounds for the current line, returning a full line_pos_iterator seems unnecessary.

line_pos_iterator now detecs underlying bidirectional iterator

---

doc/x3/tutorial/roman.qbk

error: non-local lambda expression cannot have a capture-default

Fix roman example lambda error

---

.appveyor.yml

msvc-10/11/12 is no longer supported by Boost.Variant hence Spirit cannot be used (or at least tested) with those.
So remove them.

Remove unsupported compilers from Appveyor

---

doc/qi/directive.qbk
include/boost/spirit/home/classic/tree/common.hpp
include/boost/spirit/home/support/attributes.hpp
include/boost/spirit/home/support/iterators/detail/buf_id_check_policy.hpp
include/boost/spirit/home/support/iterators/detail/fixed_size_queue_policy.hpp
include/boost/spirit/home/support/iterators/detail/functor_input_policy.hpp
include/boost/spirit/home/support/iterators/detail/split_functor_input_policy.hpp
include/boost/spirit/home/support/iterators/detail/split_std_deque_policy.hpp
include/boost/spirit/home/support/iterators/multi_pass.hpp
include/boost/spirit/home/support/iterators/multi_pass_fwd.hpp

`boost::swap` is deprecated and will be removed. Use `boost::core::invoke_swap` as a replacement, where needed.
Removed `using boost::swap` in `common.hpp`, since this is not the intended usage of Boost.Swap, and doing so did not add anything to the existing code (which already did `using std::swap`).
Corrected documentation re. compatibility with `boost::swap`/`boost::core::invoke_swap`. It does not (and never did) use member `swap()` functions, but simply forwards to either `std::swap` or the user-defined free function overload (which, in turn, may forward to the member `swap()`).

Switch to `boost::core::invoke_swap`

---

include/boost/spirit/home/karma/binary/binary.hpp

Previosuly, scoped_enum was included into karma's binary.hpp through boost/endian/detail/order.hpp. Since Boost 1.84.0 that file stopped using scoped enum and switched to use plain enum class instead; so it needs to be added here.

Fix missing includes for karma/binary

---

include/boost/spirit/home/x3/operator/sequence.hpp
test/x3/Jamfile
test/x3/operators_adl.cpp

It might be instantiated for user types inherited from classes in our namespace.
Fixes #782

X3: Constrain `operator>`

---

doc/x3/tutorial/minimal.qbk

Hi,
in the documentation were two typos:
instatntaiting -> instantiating
Rememeber -> Remember

Fix 2 Typos: instantiating and Remember

---

include/boost/spirit/home/x3/directive/confix.hpp
test/x3/confix.cpp

Part of #809 
Use concepts to constrain `x3::confix`. It is now a CPO that inhibits ADL.

Modernize `x3::confix`

---

include/boost/spirit/home/x3/core/skip_over.hpp
include/boost/spirit/home/x3/directive/lexeme.hpp
test/x3/lexeme.cpp

Part of #809 
Use concepts in `x3::lexeme` and `x3::skip_over`. `x3::lexeme` is now a CPO that inhibits ADL.

Modernize `x3::lexeme` and `x3::skip_over`

---

include/boost/spirit/home/x3/directive/matches.hpp
test/x3/matches.cpp

Part of #809 
Use concepts in `x3::matches`. It is now a CPO that inhibits ADL.

Modernize `x3::matches`

---

include/boost/spirit/home/x3/directive/repeat.hpp
test/x3/repeat.cpp
test/x3/utils.hpp

Part of #809 
- Use concepts in `x3::repeat`.
- `x3::repeat` is now a CPO that inhibits ADL.
- `x3::inf` is deprecated regarding overly generic name; use `x3::repeat_inf` instead.
- `x3::repeat[p]` is deprecated since it has the exact same meaning as `*p`. It is generally discouraged to provide multiple ways to achieve same the functionality in modern C++ library design.

Modernize `x3::repeat`
